import { SkiResortStatus, WebcamSpot } from '../types';

export const SKI_RESORTS_DATA: SkiResortStatus[] = [
  {
    id: 'skiliftkarussell-winterberg',
    name: 'Skiliftkarussell Winterberg',
    name_nl: 'Skiliftkarussell Winterberg',
    status: 'closed',
    openLifts: 0,
    totalLifts: 27,
    openSlopesKm: 0,
    totalSlopesKm: 27.5,
    snowDepthMountain: 0,
    snowDepthValley: 0,
    snowCondition: 'none',
    floodlightTonight: false,
    tobogganLiftsOpen: 0,
    crossCountryTrailsKm: 0,
    lastUpdated: 'Heute (Sommer-/Nebensaison)',
    websiteUrl: 'https://www.skiliftkarussell.de',
    description: 'Das größte zusammenhängende Skigebiet im Sauerland mit Bremberg, Poppenberg, Herrloh, Kappe und Sürenberg. 27 Liftanlagen (darunter 14 moderne Sesselbahnen) und 34 Abfahrten auf 27,5 km. Im Sommerbetrieb: Panoramabahn Kappe (Erlebnisberg/Bikepark) und Schanzenwirbel Herrloh für Ausflügler geöffnet.',
    description_nl: 'Het grootste aaneengesloten skigebied in het Sauerland met Bremberg, Poppenberg, Herrloh, Kappe en Sürenberg. 27 skiliften en 34 afdalingen. In het zomerseizoen: stoeltjeslift Kappe en Schanzenwirbel Herrloh geopend voor wandelaars en bikers.'
  },
  {
    id: 'skikarussell-altastenberg',
    name: 'Skikarussell Altastenberg',
    name_nl: 'Skicarrousel Altastenberg',
    status: 'closed',
    openLifts: 0,
    totalLifts: 7,
    openSlopesKm: 0,
    totalSlopesKm: 10.9,
    snowDepthMountain: 0,
    snowDepthValley: 0,
    snowCondition: 'none',
    floodlightTonight: false,
    tobogganLiftsOpen: 0,
    crossCountryTrailsKm: 0,
    lastUpdated: 'Heute (Sommer-/Nebensaison)',
    websiteUrl: 'https://www.ski-altastenberg.de',
    description: 'Höchstgelegenes Höhendorf im Sauerland (bis 820 m). Umfasst 7 Lifte und 17 Abfahrten inklusive der einzigen offiziellen FIS-Slalom-Weltcuppiste im Sauerland (Westfalenhang I) sowie Familien- und Panoramapisten.',
    description_nl: 'Het hoogst gelegen skidorp in het Sauerland (tot 820 m) met 7 liften, 17 pistes en de enige officiële FIS-wereldbeker slalomafdaling in de regio.'
  },
  {
    id: 'postwiese-neuastenberg',
    name: 'Postwiesen-Skigebiet Neuastenberg',
    name_nl: 'Postwiese Skigebied Neuastenberg',
    status: 'closed',
    openLifts: 0,
    totalLifts: 9,
    openSlopesKm: 0,
    totalSlopesKm: 10.0,
    snowDepthMountain: 0,
    snowDepthValley: 0,
    snowCondition: 'none',
    floodlightTonight: false,
    tobogganLiftsOpen: 0,
    crossCountryTrailsKm: 0,
    lastUpdated: 'Heute (Sommer-/Nebensaison)',
    websiteUrl: 'https://www.postwiese.de',
    description: 'Traditionsreiches Skigebiet auf der Sonnenseite des Kahlen Astens (bis 730 m) mit 9 Liften, 16 Abfahrten, Funpark, Naturrodelbahn mit eigenem Rodellift und beleuchteten Pisten (Flutlicht mittwochs, freitags und samstags).',
    description_nl: 'Zuidhelling van de Kahler Asten met 9 liften, 16 gevarieerde pistes, funpark en een professionele natuurrodelbaan.'
  },
  {
    id: 'snow-world-zueschen',
    name: 'Mein Homberg - Snow World Züschen',
    name_nl: 'Mijn Homberg - Snow World Züschen',
    status: 'closed',
    openLifts: 0,
    totalLifts: 7,
    openSlopesKm: 0,
    totalSlopesKm: 4.0,
    snowDepthMountain: 0,
    snowDepthValley: 0,
    snowCondition: 'none',
    floodlightTonight: false,
    tobogganLiftsOpen: 0,
    crossCountryTrailsKm: 0,
    lastUpdated: 'Heute (Sommer-/Nebensaison)',
    websiteUrl: 'https://www.mein-homberg.de',
    description: 'Besonders familienfreundliches Skigebiet am Homberg (bis 815 m) mit 7 Liften, sanften bis mittelschweren Hängen, Snow-Tubing-Arena, Flutlicht und der urigen Homberg-Jause.',
    description_nl: 'Gezinsvriendelijk skigebied op de Homberg (tot 815 m) met brede glooiende pistes, snow-tubingbaan en gemütliche berghut.'
  },
  {
    id: 'skigebiet-ruhrquelle',
    name: 'Skigebiet Ruhrquelle & Eschenberg',
    name_nl: 'Skigebied Ruhrquelle & Eschenberg',
    status: 'closed',
    openLifts: 0,
    totalLifts: 3,
    openSlopesKm: 0,
    totalSlopesKm: 2.5,
    snowDepthMountain: 0,
    snowDepthValley: 0,
    snowCondition: 'none',
    floodlightTonight: false,
    tobogganLiftsOpen: 0,
    crossCountryTrailsKm: 0,
    lastUpdated: 'Heute (Sommer-/Nebensaison)',
    websiteUrl: 'https://www.ruhrquelle.com',
    description: 'Direkt an der Ruhrquelle an der B480 gelegen mit 4er-Sesselbahn, Schlepplift, Flutlichtanlage und eigener Skischule mit Übungsgelände für Kinder und Einsteiger.',
    description_nl: 'Direct aan de Ruhrquelle met 4-persoons stoeltjeslift, sleeplift, verlichte avondpiste en skischool voor beginners.'
  }
];

export const WEBCAMS_DATA: WebcamSpot[] = [
  {
    id: 'cam-schanze',
    title: 'St. Georg Sprungschanze Herrloh',
    title_nl: 'St. Georg Schans bij de Herrloh',
    location: 'Winterberg Herrloh',
    altitudeMeters: 733,
    operator: 'Skiklub Winterberg / Panomax',
    previewImageUrl: 'https://images.unsplash.com/photo-1548777123-e216912df7d8?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://winterberg-schanze.panomax.com/',
    statusText: 'Live 360° Panoramakamera',
    statusText_nl: 'Live 360° Panoramacamera'
  },
  {
    id: 'cam-poppenberg',
    title: 'Skiliftkarussell Poppenberg & Möppis Hütte',
    title_nl: 'Skiliftkarussell Poppenberg & Möppis Hütte',
    location: 'Skiliftkarussell Piste 5',
    altitudeMeters: 740,
    operator: 'Skiliftkarussell Winterberg / Panomax',
    previewImageUrl: 'https://images.unsplash.com/photo-1482867996988-29ec3a0f1aac?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://winterberg-moeppi.panomax.com/',
    statusText: 'Live 360° Pistenpanorama',
    statusText_nl: 'Live 360° Pistepanorama'
  },
  {
    id: 'cam-kappe',
    title: 'Erlebnisberg Kappe & Bobbahn',
    title_nl: 'Erlebnisberg Kappe & Bobsleebaan',
    location: 'Winterberg Kappe (Talstation)',
    altitudeMeters: 720,
    operator: 'Erlebnisberg Kappe / Feratel',
    previewImageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://webtv.feratel.com/webtv/?cam=5260',
    statusText: 'Live HD Talstation',
    statusText_nl: 'Live HD Dalstation'
  },
  {
    id: 'cam-bremberg',
    title: 'Brembergkopf Sesselbahn & P1',
    title_nl: 'Bremberg Stoeltjeslift & P1',
    location: 'Skiliftkarussell Bremberg',
    altitudeMeters: 790,
    operator: 'Skiliftkarussell Winterberg / Feratel',
    previewImageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://webtv.feratel.com/webtv/?cam=5261',
    statusText: 'Live HD Sesselbahn',
    statusText_nl: 'Live HD Stoeltjeslift'
  },
  {
    id: 'cam-kahler-asten',
    title: 'Kahler Asten Wetterstation (842 m)',
    title_nl: 'Kahler Asten Weerstation (842 m)',
    location: 'Kahler Asten Astenturm',
    altitudeMeters: 842,
    operator: 'Deutscher Wetterdienst (DWD) / Sauerland Camera',
    previewImageUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://www.sauerland.camera/webcam/kahler-asten-sw/',
    statusText: '842 m DWD-Wetterturm',
    statusText_nl: '842 m Weerstation'
  },
  {
    id: 'cam-postwiese',
    title: 'Skigebiet Postwiese Neuastenberg',
    title_nl: 'Skigebied Postwiese Neuastenberg',
    location: 'Neuastenberg Postwiese',
    altitudeMeters: 730,
    operator: 'Postwiese Neuastenberg / Feratel',
    previewImageUrl: 'https://images.unsplash.com/photo-1542314831-c6a4d2757106?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://webtv.feratel.com/webtv/?cam=5262',
    statusText: 'Live HD Panoramablick',
    statusText_nl: 'Live HD Panoramabeeld'
  },
  {
    id: 'cam-altastenberg',
    title: 'Skikarussell Altastenberg (Westfalenhang)',
    title_nl: 'Skikarussell Altastenberg (Westfalenhang)',
    location: 'Altastenberg Dorf & Pisten',
    altitudeMeters: 820,
    operator: 'Verkehrsverein / Sauerland Camera',
    previewImageUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://www.sauerland.camera/webcam/altastenberg/',
    statusText: '820 m Höhendorf',
    statusText_nl: '820 m Hoogste Skidorp'
  },
  {
    id: 'cam-eisarena',
    title: 'VELTINS-EisArena (Bobbahn Winterberg)',
    title_nl: 'VELTINS-EisArena (Bobsleebaan Winterberg)',
    location: 'Erlebnisberg Kappe',
    altitudeMeters: 720,
    operator: 'Sportzentrum Winterberg Hochsauerland',
    previewImageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://www.veltins-eisarena.de/service/webcam',
    statusText: 'Weltcup-Zielkurve',
    statusText_nl: 'Wereldbeker Finish'
  }
];
