import { SkiResortStatus, WebcamSpot } from '../types';

export const SKI_RESORTS_DATA: SkiResortStatus[] = [
  {
    id: 'skiliftkarussell-winterberg',
    name: 'Skiliftkarussell Winterberg',
    name_nl: 'Skiliftkarussell Winterberg',
    status: 'open',
    openLifts: 24,
    totalLifts: 27,
    openSlopesKm: 25.5,
    totalSlopesKm: 27.5,
    snowDepthMountain: 45,
    snowDepthValley: 35,
    snowCondition: 'compact',
    floodlightTonight: true,
    tobogganLiftsOpen: 4,
    crossCountryTrailsKm: 18,
    lastUpdated: 'Heute, 08:30 Uhr',
    websiteUrl: 'https://www.skiliftkarussell.de',
    description: 'Das größte zusammenhängende Skigebiet im Sauerland mit Bremberg, Poppenberg, Herrloh, Kappe und Sürenberg. Modernste Sesselbahnen und Flutlicht mittwochs, freitags und samstags.',
    description_nl: 'Het grootste aaneengesloten skigebied in het Sauerland met Bremberg, Poppenberg, Herrloh, Kappe en Sürenberg. Moderne stoeltjesliften en avondskiën op woensdag, vrijdag en zaterdag.'
  },
  {
    id: 'skikarussell-altastenberg',
    name: 'Skikarussell Altastenberg',
    name_nl: 'Skicarrousel Altastenberg',
    status: 'open',
    openLifts: 7,
    totalLifts: 8,
    openSlopesKm: 9.5,
    totalSlopesKm: 11.0,
    snowDepthMountain: 50,
    snowDepthValley: 40,
    snowCondition: 'compact',
    floodlightTonight: false,
    tobogganLiftsOpen: 2,
    crossCountryTrailsKm: 32,
    lastUpdated: 'Heute, 08:45 Uhr',
    websiteUrl: 'https://www.ski-altastenberg.de',
    description: 'Höchstgelegenes Höhendorf im Sauerland (bis 820 m). Bietet die einzige FIS-Slalom-Weltcuppiste im Sauerland sowie weitläufige Panoramapisten.',
    description_nl: 'Het hoogst gelegen skidorp in het Sauerland (tot 820 m). Biedt de enige officiële FIS-wereldbekerafdaling in het Sauerland en prachtige uitzichten.'
  },
  {
    id: 'postwiese-neuastenberg',
    name: 'Postwiesen-Skigebiet Neuastenberg',
    name_nl: 'Postwiese Skigebied Neuastenberg',
    status: 'open',
    openLifts: 6,
    totalLifts: 7,
    openSlopesKm: 8.0,
    totalSlopesKm: 10.0,
    snowDepthMountain: 40,
    snowDepthValley: 30,
    snowCondition: 'compact',
    floodlightTonight: true,
    tobogganLiftsOpen: 1,
    crossCountryTrailsKm: 25,
    lastUpdated: 'Heute, 08:15 Uhr',
    websiteUrl: 'https://www.postwiese.de',
    description: 'Traditionsreiches Skigebiet am Südhang des Kahlen Astens mit Snowpark, Naturrodelbahn und Flutlicht.',
    description_nl: 'Traditioneel skigebied op de zuidhelling van de Kahler Asten met funpark, professionele natuurrodelbaan en avondskiën.'
  },
  {
    id: 'snow-world-zueschen',
    name: 'Mein Homberg - Snow World Züschen',
    name_nl: 'Mijn Homberg - Snow World Züschen',
    status: 'open',
    openLifts: 4,
    totalLifts: 5,
    openSlopesKm: 4.0,
    totalSlopesKm: 5.0,
    snowDepthMountain: 35,
    snowDepthValley: 25,
    snowCondition: 'compact',
    floodlightTonight: false,
    tobogganLiftsOpen: 2,
    crossCountryTrailsKm: 15,
    lastUpdated: 'Heute, 09:00 Uhr',
    websiteUrl: 'https://www.mein-homberg.de',
    description: 'Besonders familien- und kinderfreundliches Skigebiet mit sanften Hängen, Tubingbahn und gemütlicher Homberghütte.',
    description_nl: 'Bijzonder kindvriendelijk skigebied met brede, glooiende pistes, snow-tubingbaan en een gezellige bergchalet.'
  },
  {
    id: 'skigebiet-ruhrquelle',
    name: 'Skigebiet Ruhrquelle & Eschenberg',
    name_nl: 'Skigebied Ruhrquelle & Eschenberg',
    status: 'open',
    openLifts: 2,
    totalLifts: 3,
    openSlopesKm: 2.0,
    totalSlopesKm: 2.5,
    snowDepthMountain: 35,
    snowDepthValley: 30,
    snowCondition: 'compact',
    floodlightTonight: false,
    tobogganLiftsOpen: 1,
    crossCountryTrailsKm: 8,
    lastUpdated: 'Heute, 08:30 Uhr',
    websiteUrl: 'https://www.ruhrquelle.com',
    description: 'Direkt an der Bundesstraße B480 mit großer Flutlicht- und Beschneiungsanlage, Skischule und bequemen Parkplätzen direkt am Lift.',
    description_nl: 'Direct aan de B480 met uitstekende sneeuwkanonnen, ruime parkeergelegenheid aan de lift en een speciale kinderskischool.'
  }
];

export const WEBCAMS_DATA: WebcamSpot[] = [
  {
    id: 'cam-marktplatz',
    title: 'Marktplatz Winterberg (Untere Pforte)',
    title_nl: 'Marktplein Winterberg (Oude Binnenstad)',
    location: 'Winterberg Kernstadt',
    altitudeMeters: 670,
    operator: 'Stadt Winterberg / Tourismus',
    previewImageUrl: 'https://images.unsplash.com/photo-1542314831-c6a4d2757106?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://www.winterberg.de/service-kontakt/webcams/',
    statusText: 'Live HD 360°',
    statusText_nl: 'Live HD 360°'
  },
  {
    id: 'cam-kahler-asten',
    title: 'Kahler Asten Wetterstation (842 m)',
    title_nl: 'Kahler Asten Weerstation (842 m)',
    location: 'Kahler Asten Hochheide',
    altitudeMeters: 842,
    operator: 'Deutscher Wetterdienst (DWD)',
    previewImageUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://www.winterberg.de/service-kontakt/webcams/',
    statusText: 'Höchster Punkt',
    statusText_nl: 'Hoogste Punt'
  },
  {
    id: 'cam-poppenberg',
    title: 'Skiliftkarussell Poppenberg & Herrloh',
    title_nl: 'Skiliftkarussell Poppenberg & Herrloh',
    location: 'Skiliftkarussell Pisten 2 & 5',
    altitudeMeters: 740,
    operator: 'Skiliftkarussell Winterberg',
    previewImageUrl: 'https://images.unsplash.com/photo-1482867996988-29ec3a0f1aac?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://www.skiliftkarussell.de/aktuell/webcams/',
    statusText: 'Panoramakamera',
    statusText_nl: 'Panoramacamera'
  },
  {
    id: 'cam-eisarena',
    title: 'VELTINS-EisArena (Bobbahn Winterberg)',
    title_nl: 'VELTINS-EisArena (Bobsleebaan Winterberg)',
    location: 'Erlebnisberg Kappe',
    altitudeMeters: 720,
    operator: 'Sportzentrum Winterberg Hochsauerland',
    previewImageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://www.veltins-eisarena.de/service/webcam',
    statusText: 'Weltcup-Zielkurve',
    statusText_nl: 'Wereldbeker Finish'
  },
  {
    id: 'cam-st-georg',
    title: 'St. Georg Sprungschanze am Herrloh',
    title_nl: 'St. Georg Schans bij de Herrloh',
    location: 'Herrloh / Sürenberg',
    altitudeMeters: 733,
    operator: 'Skiklub Winterberg e.V.',
    previewImageUrl: 'https://images.unsplash.com/photo-1548777123-e216912df7d8?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://www.skiliftkarussell.de/aktuell/webcams/',
    statusText: 'Wahrzeichen Blick',
    statusText_nl: 'Winterberg Icoon'
  },
  {
    id: 'cam-kappe',
    title: 'Erlebnisberg Kappe & Panorama Brücke',
    title_nl: 'Erlebnisberg Kappe & Panoramabrug',
    location: 'Winterberg Kappe',
    altitudeMeters: 776,
    operator: 'Erlebnisberg Kappe / Bikepark',
    previewImageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    liveStreamUrl: 'https://www.erlebnisberg-kappe.de/service/webcams/',
    statusText: 'Bikepark & Kappe',
    statusText_nl: 'Bikepark & Piste'
  }
];
