import { Business, ThemeConfig, ThemeKey, CategoryGroup } from './types';

export const businesses: Business[] = [
  {
    id: 'rewe-winterberg',
    name: 'REWE',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'Dein REWE Supermarkt in Winterberg.',
    address: 'Poststraße 6, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 7736',
    isPremium: false,
    openingHours: {
      monday: '07:00 - 22:00',
      tuesday: '07:00 - 22:00',
      wednesday: '07:00 - 22:00',
      thursday: '07:00 - 22:00',
      friday: '07:00 - 22:00',
      saturday: '07:00 - 22:00',
      sunday: 'Geschlossen'
    }
  },
  {
    id: '142',
    name: 'Hessenkeller Winterberg',
    category: 'Gastronomie',
    subcategory: 'Kneipen und Bars',
    description: 'Kneipe in Winterberg. Beliebter Treffpunkt mit Live-Veranstaltungen, Tanzen und Quizabenden.',
    address: 'Am Waltenberg 1, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 930111',
    website: 'https://hotel-hessenhof.de',
    imageFallback: 'HK',
  },
  {
    id: '143',
    name: 'Lingenauber',
    category: 'Gastronomie',
    subcategory: 'Kneipen und Bars',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Restaurant' }
    ],
    description: 'Gastrokneipe in Siedlinghausen. Bietet Sitzplätze im Freien und Hunde sind erlaubt.',
    address: 'Hochsauerlandstraße 15, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02983 8231',
    website: 'https://lingenaubers.de',
    imageFallback: 'LI',
  },
  {
    id: '144',
    name: 'Blackwater Irish Pub Winterberg',
    category: 'Gastronomie',
    subcategory: 'Kneipen und Bars',
    description: 'Beliebte Kneipe mit traditioneller Einrichtung, irischen Bieren vom Fass und Sport auf Großbildleinwand.',
    address: 'Nuhnestraße 2, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 899539',
    website: 'https://blackwater-irishpub.de',
    imageFallback: 'BW',
  },
  {
    id: '145',
    name: 'Bu\'ket Bar Winterberg',
    category: 'Gastronomie',
    subcategory: 'Kneipen und Bars',
    description: 'Cocktailbar in Winterberg. Hunde erlaubt.',
    address: 'Poststraße 1, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 8968670',
    imageFallback: 'BK',
  },

  {
    id: '1',
    name: 'Car-Point Winterberg',
    category: 'Handwerk',
    subcategory: 'KFZ-Werkstätten',
    description: 'Wir sind Profis! Wir bieten KFZ-Reparaturen aller Art an.',
    address: 'Remmeswiese 30a, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://car-point-winterberg.de/',
    imageFallback: 'CP',
    isVerified: true
  },
  {
    id: '2',
    name: 'Autoservice Kruk',
    category: 'Handwerk',
    subcategory: 'KFZ-Werkstätten',
    description: 'Ihre freundliche Autofachwerkstatt in Winterberg-Siedlinghausen. Schnell, Preiswert & Zuverlässig.',
    address: 'Hochsauerlandstraße 78a, 59955 Winterberg',
    district: 'Siedlinghausen',
    website: 'https://www.autoservice-kruk.de/',
    imageFallback: 'AK',
  },
  {
    id: 'nagel',
    name: 'Nagel Udo Autoreparatur',
    category: 'Handwerk',
    subcategory: 'KFZ-Werkstätten',
    description: 'AUTOREPARATUREN',
    address: 'Hochsauerlandstr. 56, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02983 7 61',
    imageFallback: 'NUA',
    isVerified: true
  },
  {
    id: '3',
    name: 'HAS-Antriebstechnik Bosch Car Service',
    category: 'Handwerk',
    subcategory: 'KFZ-Werkstätten',
    description: 'Bosch Car Service und Werkstatt Dienstleistungen für alle Fabrikate in Winterberg.',
    address: 'Am Hagenblech 38, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://has-antriebstechnik.de/',
    imageFallback: 'HAS',
  },
  {
    id: '4',
    name: 'Andreas Mantel Auto & Zweirad',
    category: 'Handwerk',
    subcategory: 'KFZ-Werkstätten',
    description: 'Ihr Meisterbetrieb für Auto & Zweirad in Winterberg.',
    address: 'Ruhrstraße 69, 59955 Winterberg',
    district: 'Niedersfeld',
    website: 'https://www.mantel-kfz.de/',
    imageFallback: 'AM',
  },
  {
    id: '5',
    name: 'Schürmann & Kruse OHG',
    category: 'Handwerk',
    subcategory: 'KFZ-Werkstätten',
    description: 'Zuverlässiger Service, markenübergreifende Expertise & höchste Präzision. High-End Upgrades, Engineering und Performance-Lösungen.',
    address: 'Am Hagenblech 85, 59955 Winterberg',
    district: 'Winterberg',
    phone: '+49 151 50 70 51 44',
    website: 'https://www.schuermann-kruse.de/',
    imageFallback: 'SK',
  },
  {
    id: '6',
    name: 'Erlebnisberg Kappe',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Bikepark, Sommerrodelbahn und Kletterwald - Spaß für die ganze Familie.',
    address: 'Kappestrasse 1, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://www.erlebnisbergkappe.de/',
    imageFallback: 'EK',
  },
  {
    id: '7',
    name: 'Bröker Objekteinrichtungen GmbH & Co. KG',
    category: 'Handwerk',
    subcategory: 'Schreinereien',
    description: 'Tischler NRW - Team Compact Handwerk mit Ideen!',
    address: 'Remmeswiese 26, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92965-0',
    website: 'https://broeker-winterberg.de/',
    imageFallback: 'BO',
  },
  {
    id: '8',
    name: 'Stockhausen Treppen GmbH',
    category: 'Handwerk',
    subcategory: 'Schreinereien',
    description: 'Stockhausen Treppen - Ihr Spezialist für individuellen Treppenbau.',
    address: 'Nuhnetalstraße 132, 59955 Winterberg',
    district: 'Züschen',
    phone: '02981 8969060',
    website: 'https://stockhausen-treppen.de/',
    imageFallback: 'ST',
  },
  {
    id: '9',
    name: 'Rudolf Ittermann',
    category: 'Handwerk',
    subcategory: 'Schreinereien',
    description: 'Rudolf Ittermann Tischlerei in Winterberg.',
    address: 'Am Eschenberg 8, 59955 Winterberg',
    district: 'Niedersfeld',
    phone: '02985 8100',
    imageFallback: 'RI',
  },
  {
    id: '10',
    name: 'Daniel Sögtrop Tischlerei',
    category: 'Handwerk',
    subcategory: 'Schreinereien',
    description: 'Daniel Sögtrop Tischlerei - Ihr Ansprechpartner für Holz und Möbel.',
    address: 'Hochsauerlandstr. 72, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02983 9740310',
    website: 'https://tischlerei-soegtrop.de/',
    imageFallback: 'DS',
  },
  {
    id: '11',
    name: 'Textilreinigung Roj',
    category: 'Handwerk',
    subcategory: 'Wäschereien',
    description: 'Ihre Reinigung in Winterberg für Änderungen, Bettdeckenreinigung, Biochemische Reinigung, Bügeln und Großwäscherei.',
    address: 'Hauptstraße 15, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 5080280',
    imageFallback: 'TR',
  },
  {
    id: '12',
    name: 'Müller Michael Elektroinstallation',
    category: 'Handwerk',
    subcategory: 'Elektriker',
    description: 'Elektroinstallationen und Fachbetrieb.',
    address: 'Poststr. 9, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 22 33',
    imageFallback: 'MM',
  },
  {
    id: 'siedlinghausen-elektro-2',
    name: 'Elektro Leiße GmbH',
    description: 'Elektroinstallationen und Fachhandel in Winterberg-Siedlinghausen.',
    category: 'Handwerk',
    subcategory: 'Elektriker',
    address: 'Sorpestraße 11, 59955 Winterberg',
    phone: '02983 97000',
    email: 'info@elektro-leisse.de',
    website: 'https://elektro-leisse.de',
    district: 'Siedlinghausen',
    isPremium: false,
    services: ['Elektroinstallation', 'Kundendienst', 'Beleuchtung', 'Hausgeräte'],
    status: 'approved'
  },
  {
    id: 'mollseifer-hof',
    name: 'Mollseifer Hof Inh. Volker Geier',
    description: '',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    address: 'In d. Trift 1, 59955 Winterberg-Mollseifen',
    phone: '02981 2414',
    district: 'Mollseifen',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'eickmann-bau',
    name: 'Eickmann Bauunternehmung GmbH',
    description: '',
    category: 'Handwerk',
    subcategory: 'Bauunternehmen',
    address: 'Am Hagenblech 63, 59955 Winterberg',
    phone: '02981 92700',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'brinkmann-bau',
    name: 'Brinkmann GmbH & Co. KG',
    description: '',
    category: 'Handwerk',
    subcategory: 'Bauunternehmen',
    address: 'Remmeswiese 8, 59955 Winterberg',
    phone: '02981 1553',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'hermann-josef-kiemen',
    name: 'Hermann Josef Kiemen',
    description: '',
    category: 'Handwerk',
    subcategory: 'Elektriker',
    address: 'Briloner Str. 15, 59955 Winterberg-Siedlinghausen',
    phone: '02983 8260',
    district: 'Siedlinghausen',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'wanderlust-restaurant',
    name: 'Restaurant Wanderlust',
    description: '',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    address: 'Holtener Weg 21, 59955 Winterberg',
    phone: '02981 808135',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'bennys-kartoffelkiste',
    name: 'Benny\'s Kartoffelkiste',
    description: '',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    address: 'Am Waltenberg 45, 59955 Winterberg',
    phone: '02981 928359',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'andres-almstubn',
    name: 'AndRes Alm-Stub\'n',
    description: '',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    address: 'Hauptstraße 28, 59955 Winterberg',
    website: 'https://andres-almstubn.de',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'ritmus-restaurant',
    name: 'RitmuS - Restaurant & Tapas Bar',
    description: '',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    address: 'Kolpingstraße 12, 59955 Winterberg-Siedlinghausen',
    website: 'https://ritmus.de',
    district: 'Siedlinghausen',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'die-sperre',
    name: 'Die Sperre | Landhotel & Restaurant',
    description: '',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    address: 'Sorpestraße 80, 59955 Winterberg',
    district: 'Siedlinghausen',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'gruener-apfel',
    name: 'Grüner Apfel Bistro-Pizzeria',
    description: '',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    address: 'Inselstraße 1, 59955 Winterberg-Siedlinghausen',
    phone: '02983 8535',
    district: 'Siedlinghausen',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'restaurant-athen',
    name: 'Restaurant Athen',
    description: '',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    address: 'Hauptstraße 22, 59955 Winterberg',
    phone: '02981 7754',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'pizzahaus-winterberg',
    name: 'Pizzahaus Winterberg',
    description: '',
    category: 'Gastronomie',
    subcategory: 'Pizzerien',
    address: 'Marktstraße 12, 59955 Winterberg',
    phone: '02981 8207130',
    website: 'https://pizzahaus-winterberg.de',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'pizzeria-dani',
    name: 'Pizzeria Dani',
    description: '',
    category: 'Gastronomie',
    subcategory: 'Pizzerien',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Restaurant' }
    ],
    address: 'Am Waltenberg 27, 59955 Winterberg',
    phone: '02981 908040',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'colosseum',
    name: 'Restaurant Pizzeria Colosseum Winterberg',
    description: '',
    category: 'Gastronomie',
    subcategory: 'Pizzerien',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Restaurant' }
    ],
    address: 'Hauptstraße 7, 59955 Winterberg',
    phone: '02981 899960',
    website: 'https://colosseum-winterberg.de',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'pizzeria-venezia',
    name: 'Ristorante Pizzeria Venezia',
    description: '',
    category: 'Gastronomie',
    subcategory: 'Pizzerien',
    address: 'u. Pforte 9, 59955 Winterberg',
    phone: '02981 8993699',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'da-salvatore',
    name: 'Ristorante Da Salvatore',
    description: '',
    category: 'Gastronomie',
    subcategory: 'Pizzerien',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Restaurant' }
    ],
    address: 'Bahnhofstraße 12, 59955 Winterberg',
    phone: '02981 8995225',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'markus-klauke-gmbh',
    name: 'Markus Klauke GmbH',
    description: '',
    category: 'Handwerk',
    subcategory: 'Maler & Lackierer',
    address: 'Senge-Platten-Straße 8, 59955 Winterberg',
    phone: '02983 974390',
    district: 'Siedlinghausen',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'malerbetrieb-schnorbus',
    name: 'Malerbetrieb Schnorbus',
    description: '',
    category: 'Handwerk',
    subcategory: 'Maler & Lackierer',
    address: 'Oberstraße 12, 59955 Winterberg',
    phone: '02981 928737',
    district: 'Züschen',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'maler-leber',
    name: 'Maler Leber Inh. Christopher Seston - Maler Winterberg / Brilon',
    description: '',
    category: 'Handwerk',
    subcategory: 'Maler & Lackierer',
    address: 'Eichendorffsiedlung 12, 59955 Winterberg',
    phone: '02981 1273',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'gartenbau-biene',
    name: 'Gartenbau Biene',
    description: '',
    category: 'Handwerk',
    subcategory: 'Gartenbauer',
    address: 'Am Iberg 7, 59955 Winterberg',
    phone: '02983 9706466',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'garna-garten',
    name: 'GarNa; Garten und Natur',
    description: '',
    category: 'Handwerk',
    subcategory: 'Gartenbauer',
    address: 'Sorpestraße 34a, 59955 Winterberg',
    district: 'Siedlinghausen',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'tielke-garten',
    name: 'Tielke Garten-und Landschaftsbau',
    description: '',
    category: 'Handwerk',
    subcategory: 'Gartenbauer',
    address: 'Ockelsbach 2, 59955 Winterberg',
    phone: '02981 5089224',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'ralph-luetteken',
    name: 'Ralph Lütteken GmbH',
    description: '',
    category: 'Handwerk',
    subcategory: 'Gartenbauer',
    address: 'Burmeckestraße 10, 59955 Winterberg',
    phone: '02983 21568',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'creative-garden',
    name: 'CREATIVE GARDEN',
    description: '',
    category: 'Handwerk',
    subcategory: 'Gartenbauer',
    address: 'Jakobusstraße 23, 59955 Winterberg',
    phone: '0160 1703131',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'santherm-heizung',
    name: 'SanTHERM Heizung Sanitär Klima Haustechnik GmbH',
    description: '',
    category: 'Handwerk',
    subcategory: 'Heizungstechnik',
    address: 'Lamfert 11, 59955 Winterberg',
    phone: '02981 92520',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'lefarth-braun',
    name: 'Lefarth & Braun Haustechnik GmbH',
    description: '',
    category: 'Handwerk',
    subcategory: 'Heizungstechnik',
    address: 'Am Hagenblech 3, 59955 Winterberg',
    phone: '02981 927190',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'schoermann',
    name: 'Sanitär Heizung Klima Solar Schörmann',
    description: '',
    category: 'Handwerk',
    subcategory: 'Heizungstechnik',
    address: 'Nuhnestraße 3, 59955 Winterberg',
    phone: '02981 92830',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: '3werk-haustechnik',
    name: '3WERK Haustechnik GmbH & Co.KG',
    description: '',
    category: 'Handwerk',
    subcategory: 'Heizungstechnik',
    address: 'Remmeswiese 28, 59955 Winterberg',
    phone: '02981 896960',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'jens-winzenick',
    name: 'Jens Winzenick',
    description: '',
    category: 'Handwerk',
    subcategory: 'Heizungstechnik',
    address: 'Remmeswiese 1B, 59955 Winterberg',
    phone: '02981 573',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'senge-gmbh',
    name: 'Senge GmbH | Heizung-Solar-Sanitär',
    description: '',
    category: 'Handwerk',
    subcategory: 'Heizungstechnik',
    address: 'Kolpingstraße 19, 59955 Winterberg-Siedlinghausen',
    phone: '02983 8214',
    district: 'Siedlinghausen',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'atmos-ecoheat',
    name: 'ATMOS EcoHeat - Effiziente Direktheizungen & Heizkörper',
    description: '',
    category: 'Handwerk',
    subcategory: 'Heizungstechnik',
    address: 'Allenbergstraße 26, 59955 Winterberg',
    phone: '02983 891056',
    district: 'Siedlinghausen',
    isPremium: false,
    status: 'approved'
  },
  {
    id: '13',
    name: 'Quick Reiner Elektroinstallation',
    category: 'Handwerk',
    subcategory: 'Elektriker',
    description: 'Elektroinstallationen',
    address: 'Hellenstr. 54, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 24 64',
    imageFallback: 'QR',
  },
  {
    id: '14',
    name: 'Kösler Elektro',
    category: 'Handwerk',
    subcategory: 'Elektriker',
    description: 'Elektroinstallationen',
    address: 'Schanzenstr. 16, 59955 Winterberg',
    district: 'Winterberg',
    phone: '0173 5 17 71 51',
    imageFallback: 'KE',
  },
  {
    id: '15',
    name: 'Kiemen Hermann J. Elektroinstallation',
    category: 'Handwerk',
    subcategory: 'Elektriker',
    description: 'Elektroinstallationen',
    address: 'Briloner Str. 15, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02983 82 60',
    imageFallback: 'HK',
  },
  {
    id: '16',
    name: 'Meisterbetrieb Menke',
    category: 'Handwerk',
    subcategory: 'Dachdecker',
    description: 'Dachdecker Meisterbetrieb',
    address: 'Am Iberg 2, 59955 Winterberg',
    district: 'Silbach',
    phone: '02983 1404',
    website: 'mailto:info@meisterbetrieb-menke.de',
    imageFallback: 'MM',
  },
  {
    id: '17',
    name: 'Müllenhoff Winterberg Bedachungs GmbH',
    category: 'Handwerk',
    subcategory: 'Dachdecker',
    description: 'Bedachungen',
    address: 'Remmeswiese 1, 59955 Winterberg',
    district: 'Winterberg',
    phone: '+49 2981 472',
    imageFallback: 'MW',
  },
  {
    id: '18',
    name: 'Schindel Dachdeckermeister',
    category: 'Handwerk',
    subcategory: 'Dachdecker',
    description: 'Dachdeckermeister Schindel',
    address: 'Kirchstr. 13, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 8160938',
    website: 'mailto:info@ddm-schindel.de',
    imageFallback: 'SD',
  },
  {
    id: '19',
    name: 'Netto Marken-Discount',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'Lebensmittel, frische Backwaren, Obst und Gemüse.',
    address: 'Hochsauerlandstr. 60, 59955 Winterberg',
    district: 'Siedlinghausen',
    website: 'https://www.netto-online.de/',
    imageFallback: 'NM',
    openingHours: {
      monday: '07:00 - 20:00',
      tuesday: '07:00 - 20:00',
      wednesday: '07:00 - 20:00',
      thursday: '07:00 - 20:00',
      friday: '07:00 - 20:00',
      saturday: '07:00 - 20:00',
      sunday: 'Geschlossen'
    }
  },
  {
    id: '20',
    name: 'Netto Marken-Discount',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'Lebensmittel, frische Backwaren, Obst und Gemüse.',
    address: 'Ruhrstr. 4, 59955 Winterberg',
    district: 'Niedersfeld',
    website: 'https://www.netto-online.de/',
    imageFallback: 'NM',
    openingHours: {
      monday: '07:00 - 20:00',
      tuesday: '07:00 - 20:00',
      wednesday: '07:00 - 20:00',
      thursday: '07:00 - 20:00',
      friday: '07:00 - 20:00',
      saturday: '07:00 - 20:00',
      sunday: 'Geschlossen'
    }
  },
  {
    id: '21',
    name: 'Lidl',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'Beste Qualität zum niedrigen Preis.',
    address: 'Im Mühlengrund 1, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://www.lidl.de/',
    imageFallback: 'LI',
    openingHours: {
      monday: '07:00 - 21:00',
      tuesday: '07:00 - 21:00',
      wednesday: '07:00 - 21:00',
      thursday: '07:00 - 21:00',
      friday: '07:00 - 21:00',
      saturday: '07:00 - 21:00',
      sunday: 'Geschlossen'
    }
  },
  {
    id: '22',
    name: 'E center Löffler',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'EDEKA Löffler - Frische und Vielfalt im Herzen von Winterberg.',
    address: 'Neue Mitte 4, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://www.edeka.de/',
    imageFallback: 'EL',
    openingHours: {
      monday: '07:00 - 21:00',
      tuesday: '07:00 - 21:00',
      wednesday: '07:00 - 21:00',
      thursday: '07:00 - 21:00',
      friday: '07:00 - 21:00',
      saturday: '07:00 - 21:00',
      sunday: 'Geschlossen'
    }
  },
  {
    id: '23',
    name: 'ALDI Nord',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'Hochwertige Produkte zum Original ALDI Preis.',
    address: 'Neue Mitte 3, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://www.aldi-nord.de/',
    imageFallback: 'AN',
    openingHours: {
      monday: '07:00 - 20:00',
      tuesday: '07:00 - 20:00',
      wednesday: '07:00 - 20:00',
      thursday: '07:00 - 20:00',
      friday: '07:00 - 20:00',
      saturday: '07:00 - 20:00',
      sunday: 'Geschlossen'
    }
  },
  {
    id: '24',
    name: 'Dorfladen Wilmes',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'Lebensmittel und Artikel für den täglichen Bedarf.',
    address: 'Wiesenstr. 12, 59955 Winterberg',
    district: 'Silbach',
    phone: '02983 1774',
    imageFallback: 'DW',
  },
  {
    id: '25',
    name: 'EDEKA Lingenauber',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'EDEKA Markt mit vielfältigem Sortiment.',
    address: 'Nuhnetalstraße 46, 59955 Winterberg',
    district: 'Züschen',
    website: 'https://www.edeka.de/',
    imageFallback: 'EL',
    openingHours: {
      monday: '07:00 - 20:00',
      tuesday: '07:00 - 20:00',
      wednesday: '07:00 - 20:00',
      thursday: '07:00 - 20:00',
      friday: '07:00 - 20:00',
      saturday: '07:00 - 20:00',
      sunday: 'Geschlossen'
    }
  },
  {
    id: '26',
    name: 'Tennisplätze Niedersfeld',
    category: 'Freizeit',
    subcategory: 'Tennisplätze',
    description: 'Tennisverein in Niedersfeld mit 3 Sandplätzen.',
    address: 'An der Hille 6b, 59955 Winterberg',
    district: 'Niedersfeld',
    website: 'http://www.sv-niedersfeld.de',
    imageFallback: 'SVN',
  },
  {
    id: '27',
    name: 'Tennisplätze Züschen',
    category: 'Freizeit',
    subcategory: 'Tennisplätze',
    description: 'Tennisverein in Züschen mit Sandplätzen.',
    address: 'Schützenstraße 5, 59955 Winterberg',
    district: 'Züschen',
    phone: '02981 2541',
    imageFallback: 'TUS',
  },
  {
    id: '28',
    name: 'Tennisplätze Winterberg',
    category: 'Freizeit',
    subcategory: 'Tennisplätze',
    description: 'Tennisverein in Winterberg Winterberg mit Sandplätzen.',
    address: 'Fichtenweg 14, 59955 Winterberg',
    district: 'Winterberg',
    website: 'http://www.tc-winterberg.de',
    imageFallback: 'TC',
  },
  {
    id: '29',
    name: 'Tennisplätze Siedlinghausen',
    category: 'Freizeit',
    subcategory: 'Tennisplätze',
    description: 'Tennisverein in Siedlinghausen (keine Sandplätze).',
    address: 'Grimmeweg 9, 59955 Winterberg',
    district: 'Siedlinghausen',
    website: 'mailto:bm.hoemberg@gmail.com',
    imageFallback: 'TC',
  },
  {
    id: '30',
    name: 'VfR Winterberg 1921 e.V.',
    category: 'Freizeit',
    subcategory: 'Fußballvereine',
    description: 'Fußballverein in Winterberg Winterberg.',
    address: 'Oberhofer Weg 9, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02985 979916',
    email: 'info@vfr-winterberg.de',
    website: 'http://vfr-winterberg.de/',
    imageFallback: 'VfR',
  },
  {
    id: '31',
    name: 'TuS Züschen e.V.',
    category: 'Freizeit',
    subcategory: 'Fußballvereine',
    description: 'Fußball- und Sportverein in Züschen.',
    address: 'Junkerstraße 38, 59955 Winterberg',
    district: 'Züschen',
    email: 'vorstand@tus-zueschen.de',
    website: 'http://www.tus-zueschen.de/',
    imageFallback: 'TuS',
  },
  {
    id: '32',
    name: 'Spiel- und Sportverein Silbach 1923 e.V.',
    category: 'Freizeit',
    subcategory: 'Fußballvereine',
    description: 'Sportverein in Silbach.',
    address: 'Am Schieferberg 2, 59955 Winterberg',
    district: 'Silbach',
    imageFallback: 'SSV',
  },
  {
    id: '33',
    name: 'FC Siedlinghausen 1920 e.V',
    category: 'Freizeit',
    subcategory: 'Fußballvereine',
    description: 'Fußballabteilung (2 Seniorenmannschaften und mehrere Jugendmannschaften), Breitensport (Gymnastik und Faszientraining), Wirbelsäulengymnastik, Qi Gong, Meditation.',
    address: 'Sorpestraße 41, 59955 Winterberg',
    district: 'Siedlinghausen',
    email: 'trippemichael17@gmail.com',
    imageFallback: 'FCS',
  },
  {
    id: '34',
    name: 'FC Hilletal 2003',
    category: 'Freizeit',
    subcategory: 'Fußballvereine',
    description: 'Fußballverein in Niedersfeld.',
    address: 'An der Hille 6 a, 59955 Winterberg',
    district: 'Niedersfeld',
    phone: '02985 979916',
    email: 'info@fc-hilletal.de',
    website: 'http://www.fc-hilletal.de/',
    imageFallback: 'FCH',
  },
  {
    id: '35',
    name: 'CEB-Steuerberater',
    category: 'Dienstleistungen',
    subcategory: 'Steuerberater',
    description: 'Ihre Steuerberatung in Winterberg.',
    address: 'Hauptstraße 26, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92560',
    imageFallback: 'CEB',
  },
  {
    id: '36',
    name: 'Kruse Brickenstein & Partner',
    category: 'Dienstleistungen',
    subcategory: 'Steuerberater',
    description: 'Wirtschaftsprüfer und Steuerberater.',
    address: 'Franziskusstraße 9, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92060',
    imageFallback: 'KBP',
  },
  {
    id: '37',
    name: 'Wingenbach & Partner mbB',
    category: 'Dienstleistungen',
    subcategory: 'Steuerberater',
    description: 'Steuerberater in Silbach.',
    address: 'Wiesenstraße 35, 59955 Winterberg',
    district: 'Silbach',
    phone: '02983 969260',
    imageFallback: 'WP',
  },
  {
    id: '38',
    name: 'BSK Steuerberatung GmbH',
    category: 'Dienstleistungen',
    subcategory: 'Steuerberater',
    description: 'Steuerberatungsgesellschaft in Züschen.',
    address: 'An d. Ebenau 4, 59955 Winterberg',
    district: 'Züschen',
    phone: '02981 92530',
    imageFallback: 'BSK',
  },
  {
    id: '39',
    name: 'Lückel & Partner',
    category: 'Dienstleistungen',
    subcategory: 'Steuerberater',
    description: 'Unternehmens- und Steuerberatung in Siedlinghausen.',
    address: 'Hochsauerlandstraße 78b, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02751 93636',
    imageFallback: 'LP',
  },
  {
    id: '40',
    name: 'Werbeagentur netzpepper',
    category: 'Dienstleistungen',
    subcategory: 'Marketingdienstleistungen',
    description: 'Werbeagentur und Webdesign in Winterberg.',
    address: 'Wernsdorfer Str. 1, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9287580',
    imageFallback: 'WN',
  },
  {
    id: '41',
    name: 'DIVE INN GmbH',
    category: 'Dienstleistungen',
    subcategory: 'Marketingdienstleistungen',
    description: 'Werbeagentur für ganzheitliche Kommunikation.',
    address: 'Remmeswiese 30, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9879997',
    imageFallback: 'DI',
  },
  {
    id: '42',
    name: 'Werbeagentur WERBSTATT',
    category: 'Dienstleistungen',
    subcategory: 'Marketingdienstleistungen',
    description: 'Ihre Werbeagentur in Siedlinghausen.',
    address: 'Senge-Platten-Straße 2, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02983 1632',
    imageFallback: 'WW',
  },
  {
    id: '43',
    name: 'Jeffry Chust Design und Advertising e.K.',
    category: 'Dienstleistungen',
    subcategory: 'Marketingdienstleistungen',
    description: 'Design und Advertising in Winterberg.',
    address: 'Oberhofer Weg 8, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'JC',
  },
  {
    id: '44',
    name: 'SICHTBAR SEO - Simon Kräling',
    category: 'Dienstleistungen',
    subcategory: 'Marketingdienstleistungen',
    description: 'Simon Kräling ist Berater für digitale Sichtbarkeit aus Winterberg im Sauerland. Er unterstützt Unternehmen branchenübergreifend dabei, ihre Zielgruppen genau dort zu erreichen, wo sie suchen: in klassischen Suchmaschinen sowie in modernen KI-Suchsystemen (Generative Engine Optimization - GEO). Durch diese Kombination verbindet er technisches Know-how mit praxisnahen Strategien. So schafft er für seine Kunden mehr digitale Unabhängigkeit und messbaren Erfolg.',
    isPremium: true,
    address: 'Schanzenstraße 28, 59955 Winterberg',
    district: 'Winterberg',
    phone: '01520 6542996',
    imageFallback: 'SS',
  },
  {
    id: '45',
    name: 'Matthias Rappel Rechtsanwalt und Notar',
    category: 'Dienstleistungen',
    subcategory: 'Rechtsanwälte',
    description: 'Rechtsanwalt und Notar in Winterberg.',
    address: '59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92090',
    imageFallback: 'MR',
  },
  {
    id: '46',
    name: 'Rechtsanwalt Ralph Schmitz-Engemann',
    category: 'Dienstleistungen',
    subcategory: 'Rechtsanwälte',
    description: 'Rechtsanwalt in Winterberg.',
    address: '59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 6751',
    imageFallback: 'RS',
  },
  {
    id: '47',
    name: 'Volker Wulf Rechtsanwalt',
    category: 'Dienstleistungen',
    subcategory: 'Rechtsanwälte',
    description: 'Rechtsanwalt in Winterberg.',
    address: '59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92210',
    imageFallback: 'VW',
  },
  {
    id: '48',
    name: 'Marion Stockhausen Rechtsanwältin',
    category: 'Dienstleistungen',
    subcategory: 'Rechtsanwälte',
    description: 'Rechtsanwältin in Winterberg.',
    address: '59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 7001',
    imageFallback: 'MS',
  },
  {
    id: '49',
    name: 'Schliwa Peter Rechtsanwalt',
    category: 'Dienstleistungen',
    subcategory: 'Rechtsanwälte',
    description: 'Rechtsanwalt in Winterberg.',
    address: '59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 3883',
    imageFallback: 'SP',
  },
  {
    id: '100',
    name: 'Insider Fashion Store Winterberg',
    category: 'Einzelhandel',
    subcategory: 'Bekleidung',
    description: 'Bekleidungsgeschäft',
    address: 'Am Waltenberg 21, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9277788',
    imageFallback: 'IF',
  },
  {
    id: '101',
    name: 'Street Point Winterberg',
    category: 'Einzelhandel',
    subcategory: 'Bekleidung',
    description: 'Bekleidungsgeschäft',
    address: 'Hauptstraße 4, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 899500',
    imageFallback: 'SP',
  },
  {
    id: '102',
    name: 'MODEORTH Winterberg GmbH',
    category: 'Einzelhandel',
    subcategory: 'Bekleidung',
    description: 'Herrenmodengeschäft',
    address: 'Hauptstraße 11, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 1775',
    imageFallback: 'MW',
  },
  {
    id: '103',
    name: 'Lütkemeier Modehaus',
    category: 'Einzelhandel',
    subcategory: 'Bekleidung',
    description: 'Bekleidungsgeschäft',
    address: 'Am Waltenberg 30, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 6013',
    imageFallback: 'LM',
  },
  {
    id: '104',
    name: 'Bessmann Mode & Sport (Outlet)',
    category: 'Einzelhandel',
    subcategory: 'Bekleidung',
    description: 'Bekleidungsgeschäft (Outlet)',
    address: 'Neue Mitte 3, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 8994180',
    imageFallback: 'BM',
  },
  {
    id: '105',
    name: 'Zeitlos',
    category: 'Einzelhandel',
    subcategory: 'Bekleidung',
    description: 'Bekleidungsgeschäft',
    address: 'Am Waltenberg 19, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 7937',
    imageFallback: 'ZL',
  },
  {
    id: '106',
    name: 'K-OFFICE BÜRODESIGN',
    category: 'Einzelhandel',
    subcategory: 'Bürobedarf',
    description: 'Bürodesign und individuelle Beratung. Vertrieb von Büroeinrichtungen. Inhaber: Burkhard Kräling.',
    address: 'Buchenweg 17, 59955 Winterberg',
    district: 'Winterberg',
    phone: '0170 220 1240',
    email: 'info@k-office.eu',
    imageFallback: 'KO',
  },
  {
    id: '107',
    name: 'Dorf Alm Winterberg',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Tiroler Küche in traditionellem Ambiente.',
    address: 'Am Waltenberg 35, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'DA',
  },
  {
    id: '108',
    name: 'Restaurant Heimatliebe',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Gemütliches Lokal mit Hausmannskost',
    address: 'Am Waltenberg 2, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'RH',
  },
  {
    id: '109',
    name: 'Restaurant Rot & Kehlchen',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Restaurant',
    address: 'Hellenstraße 2, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'RK',
  },
  {
    id: '110',
    name: 'Restaurant Forsthaus',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Restaurant',
    address: 'Orkestraße 14, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'RF',
  },
  {
    id: '111',
    name: 'Bistorant Uppu',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Einfaches Lokal für Burger und Brunch',
    address: 'Am Waltenberg 19, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'BU',
  },
  {
    id: '112',
    name: 'Restaurant Bödefelder',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Restaurant',
    address: 'Hauptstraße 3, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'RB',
  },
  {
    id: '113',
    name: 'Pasta & Wine Winterberg',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Zwangloses Lokal für italienische Pasta',
    address: 'Am Waltenberg 34, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'PW',
  },
  {
    id: '114',
    name: 'Restaurant - Der Brabander',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Restaurant',
    address: 'Am Waltenberg 63, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'DB',
  },
  {
    id: '115',
    name: 'Die Sperre',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Restaurant',
    address: 'Sorpestraße 80, 59955 Winterberg',
    district: 'Siedlinghausen',
    imageFallback: 'DS',
  },
  {
    id: '116',
    name: 'Panorama Restaurant & Café',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Bergpanorama und internationale Speisen',
    address: 'Kappe 2d, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'PR',
  },
  {
    id: '117',
    name: 'Sparkasse Mitten im Sauerland - BeratungsCenter',
    category: 'Dienstleistungen',
    subcategory: 'Banken',
    description: 'Bank und Serviceleistungen.',
    address: 'Am Waltenberg 23, 59955 Winterberg',
    district: 'Winterberg',
    phone: '0291 2080',
    imageFallback: 'SM',
  },
  {
    id: '118',
    name: 'Volksbank Sauerland eG, Beratungszentrum Winterberg',
    category: 'Dienstleistungen',
    subcategory: 'Banken',
    description: 'Bank und Beratungszentrum.',
    address: 'Poststraße 3, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92900',
    imageFallback: 'VB',
  },
  {
    id: '119',
    name: 'Sparkasse Mitten im Sauerland BeratungsCenter Siedlinghausen',
    category: 'Dienstleistungen',
    subcategory: 'Banken',
    description: 'Bank und Serviceleistungen.',
    address: 'Hochsauerlandstr. 17, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '0291 2080',
    email: 'info@sparkasse-mis.de',
    imageFallback: 'SM',
  },
  {
    id: '120',
    name: 'Sparkasse Mitten im Sauerland - SB Center',
    category: 'Dienstleistungen',
    subcategory: 'Banken',
    description: 'Geldtransferdienst und Bank.',
    address: 'Nuhnetalstraße 54, 59955 Winterberg',
    district: 'Züschen',
    phone: '0291 2080',
    imageFallback: 'SM',
  },
  {
    id: '121',
    name: 'Sparkasse Mitten im Sauerland - BeratungsCenter',
    category: 'Dienstleistungen',
    subcategory: 'Banken',
    description: 'Bank und Serviceleistungen.',
    address: 'Ruhrstraße 34, 59955 Winterberg',
    district: 'Niedersfeld',
    phone: '0291 2080',
    imageFallback: 'SM',
  },
  {
    id: '122',
    name: 'Volksbank Brilon, Filiale Niedersfeld',
    category: 'Dienstleistungen',
    subcategory: 'Banken',
    description: 'Bank und Serviceleistungen.',
    address: 'Ruhrstraße 24-26, 59955 Winterberg',
    district: 'Niedersfeld',
    phone: '02985 425',
    imageFallback: 'VB',
  },
  {
    id: '123',
    name: 'Kletterwald Winterberg - Erlebnisberg Kappe',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Klettern - Erlebnisberg Kappe.',
    address: 'Am Waltenberg 115, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9296433',
    website: 'https://www.erlebnisbergkappe.de/',
    imageFallback: 'KW',
  },
  {
    id: '124',
    name: 'BIKEPARK WINTERBERG',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Bikepark am Berghang mit Sesselliften zu den Bergstrecken im Wald sowie ein Bikeverleih.',
    address: 'Kapperundweg 3, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://www.erlebnisbergkappe.de/',
    imageFallback: 'BW',
  },
  {
    id: '125',
    name: 'Panorama-Erlebnis-Brücke',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Die Panorama-Erlebnis-Brücke in Winterberg mit Aussichtsplattformen.',
    address: 'Kappe 2c, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9296433',
    website: 'https://www.erlebnisbergkappe.de/',
    imageFallback: 'PB',
  },
  {
    id: '126',
    name: 'Abenteuergolf Winterberg - Erlebnisberg Kappe',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Minigolfplatz am Erlebnisberg Kappe.',
    address: 'Kappe, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9296433',
    website: 'https://www.erlebnisbergkappe.de/',
    imageFallback: 'AW',
  },
  {
    id: '127',
    name: 'Sommerrodelbahn Winterberg - Erlebnisberg Kappe',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Das Herzstück am Erlebnisberg Kappe, beliebt bei Groß und Klein.',
    address: 'Kappe 2b, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9296433',
    website: 'https://www.erlebnisbergkappe.de/',
    imageFallback: 'SW',
  },
  {
    id: '128',
    name: 'Adventure Golf Winterberg',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Gespielt wird auf abwechslungsreichen Bahnen mit verschiedenen Hindernissen.',
    address: 'Am Sportpl. 4, 59955 Winterberg',
    district: 'Grönebach',
    phone: '02985 9698636',
    website: 'https://adventuregolf-winterberg.de',
    imageFallback: 'AG',
  },
  {
    id: '129',
    name: 'Holocafé Winterberg - Virtual Reality Gaming',
    category: 'Freizeit',
    subcategory: 'Indoor-Spielplätze',
    description: 'Virtual Reality Gaming (ideal für Familien, JGAs, Events oder als Indoor-Schlechtwetteralternative)',
    address: 'Remmeswiese 3, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9277650',
    website: 'https://holocafe.de',
    imageFallback: 'HC',
  },
  {
    id: '130',
    name: 'Indoor Arena Full-One Lasertag Winterberg',
    category: 'Freizeit',
    subcategory: 'Indoor-Spielplätze',
    description: 'Indoor Arena Full-One Lasertag Winterberg für Kindergeburtstage, JGAs & Events – die ideale Schlechtwetter-Alternative und Action für Gruppen.',
    address: 'Remmeswiese 3, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9283918',
    website: 'https://full-one-lasertag-winterberg.de',
    imageFallback: 'FL',
    isPremium: false,
    status: 'approved'
  },
  {
    id: '131',
    name: 'Autohaus Friedrich Hoffmann',
    category: 'Einzelhandel',
    subcategory: 'Autohäuser',
    description: 'Ihr VW, Audi & VW Nutzfahrzeuge Autohaus in Winterberg. Erstklassiger Service rund um Ihr Auto.',
    address: 'Remmeswiese 24, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92070',
    website: 'https://www.friedrich-hoffmann.de',
    imageFallback: 'AH',
  },
  {
    id: '132',
    name: 'Autohaus Pöllmann',
    category: 'Einzelhandel',
    subcategory: 'Autohäuser',
    description: 'Ihr Toyota Servicepartner sowie Neuwagen, Gebrauchtwagen, Werkstatt weiterer Marken.',
    address: 'Remmeswiese 22, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92940',
    website: 'https://www.autohaus-poellmann.de',
    imageFallback: 'AP',
  },
  {
    id: '133',
    name: 'Schütte-Automobile',
    category: 'Einzelhandel',
    subcategory: 'Autohäuser',
    description: 'Autohändler in Winterberg. Verkauf von Neu- und Gebrauchtwagen.',
    address: 'Remmeswiese 2a, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 928190',
    website: 'https://www.schuette-automobile.de',
    imageFallback: 'AS',
  },
  {
    id: '134',
    name: 'UplandParcs Sauerland',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Ferienparks',
    description: 'Erleben Sie einen traumhaften Urlaub im UplandParcs Sauerland! Luxuriöse Unterkünfte inmitten der Natur.',
    address: 'Winterberg',
    district: 'Winterberg',
    website: 'https://www.uplandparcs.de',
    imageFallback: 'UPS',
  },
  {
    id: '135',
    name: 'UplandParcs Winterberg',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Ferienparks',
    description: 'Entdecken Sie UplandParcs Winterberg - luxuriöse Ferienhäuser in toller Lage. Ideal für Familien und Aktivurlauber.',
    address: 'Winterberg',
    district: 'Winterberg',
    website: 'https://www.uplandparcs.de',
    imageFallback: 'UPW',
  },
  {
    id: '136',
    name: 'UplandParcs Bergblick',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Ferienwohnungen',
    description: 'Ferienwohnung mit fantastischem Bergblick.',
    address: 'Winterberg',
    district: 'Winterberg',
    website: 'https://www.uplandparcs.de',
    imageFallback: 'UPB',
  },
  {
    id: '137',
    name: 'UplandParcs Bergresidence',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Ferienwohnungen',
    description: 'Luxuriöse Ferienwohnung Bergresidence.',
    address: 'Holtener Weg, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://www.uplandparcs.de',
    imageFallback: 'UPR',
  },
  {
    id: '138',
    name: 'UplandParcs Dumel',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Ferienhäuser',
    description: 'Komfortables Ferienhaus Dumel für einen entspannten Aufenthalt.',
    address: 'Winterberg',
    district: 'Winterberg',
    website: 'https://www.uplandparcs.de',
    imageFallback: 'UPD',
  },
  {
    id: '139',
    name: 'Hapimag Resort Winterberg',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Ferienparks',
    description: 'Hapimag Resort in Winterberg. Urlaub für die ganze Familie mit Wellness und tollen Aktivitäten.',
    address: 'Holzruhrstraße 1, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 8080',
    website: 'https://www.hapimag.com',
    imageFallback: 'HM',
  },
  {
    id: '140',
    name: 'Der Brabander',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Hotels',
    description: 'Das bekannte und beliebte Hotel in Winterberg. Wellness, Gastronomie und direkte Nähe zum Skilift.',
    address: 'Am Waltenberg 65, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9320',
    website: 'https://www.brabander.nl',
    imageFallback: 'DB',
  },
  {
    id: 'daswerk-friseure',
    name: 'DasWERK - Die Friseure',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon in Winterberg.',
    address: 'Hochsauerlandstraße 78b, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02983 9799788',
    isPremium: false,
    imageFallback: 'DW'
  },
  {
    id: 'hair-anselm-winkler',
    name: 'Hair by Anselm Winkler',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon mit Dienstleistungen wie Haarefärben, Haarstyling, Balayage, Blow-out und Dauerwellen.',
    address: 'Wernsdorfer Str. 2, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 1399',
    isPremium: false,
    imageFallback: 'HW'
  },
  {
    id: 'winterberger-barber-simply-hair',
    name: 'Winterberger Barber: Simply Hair',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Herrenfriseur in Winterberg.',
    address: 'Am Waltenberg 50, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9255808',
    website: 'https://winterbergerbarber.de',
    isPremium: false,
    imageFallback: 'SH'
  },
  {
    id: 'brieden-friseur',
    name: 'Brieden - Ihr Friseur in Winterberg',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Ihr Friseur in Winterberg. Spezialisiert auf Haarefärben und Haarstyling.',
    address: 'Hagenstraße 8, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 413',
    isPremium: false,
    imageFallback: 'BF'
  },
  {
    id: 'amers-style',
    name: "Amer's Style",
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon. Dienstleistungen umfassen Haarstyling, Haarefärben und Augenbrauen zupfen.',
    address: 'Hauptstraße 5, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9271848',
    isPremium: false,
    imageFallback: 'AS'
  },
  {
    id: 'haarschneiderei',
    name: 'Haarschneiderei',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon in Winterberg mit Fokus auf Haarefärben und Haarstyling.',
    address: 'Marktstraße 24, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 899898',
    isPremium: false,
    imageFallback: 'HS'
  },
  {
    id: 'hairfeeling-kai-padberg',
    name: 'Hairfeeling Kai Padberg',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon im Ortsteil Hildfeld.',
    address: 'Hildfelder Str. 37, 59955 Winterberg',
    district: 'Hildfeld',
    phone: '02985 1046',
    isPremium: false,
    imageFallback: 'KP'
  },
  {
    id: 'hairlounge-by-hannah',
    name: 'Hairlounge by Hannah',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon in Züschen.',
    address: 'Mittelstraße 20, 59955 Winterberg',
    district: 'Züschen',
    isPremium: false,
    imageFallback: 'HH'
  },
  {
    id: 'friseursalon-koch',
    name: 'Friseursalon Koch',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon im Ortsteil Züschen.',
    address: 'Mollseifener Str. 2, 59955 Winterberg',
    district: 'Züschen',
    phone: '02981 6899',
    isPremium: false,
    imageFallback: 'FK'
  },
  {
    id: 'cutja',
    name: 'Cutja',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon in Siedlinghausen. Spezialisiert auf Brautfrisuren, Flechtfrisuren und Hochsteckfrisuren.',
    address: 'Negertstraße 1, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02983 1256',
    isPremium: false,
    imageFallback: 'CJ'
  },
  {
    id: 'weinlaedchen-pfaelzer',
    name: 'Weinlädchen, Pfälzer',
    category: 'Gastronomie',
    subcategory: 'Weinstuben',
    description: '',
    address: 'Hauptstraße 32, 59955 Winterberg',
    phone: '0171 9059652',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'wineland',
    name: 'Wineland',
    category: 'Gastronomie',
    subcategory: 'Weinstuben',
    description: '',
    address: 'Am Waltenberg 16, 59955 Winterberg',
    phone: '02981 5089640',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'gasthof-zur-post-neuastenberg',
    name: 'Hotel Gasthof zur Post Neuastenberg',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    additionalCategories: [{ category: 'Hotels und Unterkünfte', subcategory: 'Hotels' }],
    description: '',
    address: 'Neuastenberger Str. 49, 59955 Winterberg-Neuastenberg',
    district: 'Neuastenberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'clemens-altastenberg',
    name: 'Restaurant Clemens Altastenberg',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: '',
    address: 'Renauweg 48, 59955 Winterberg',
    phone: '02981 92410',
    website: 'https://hotel-clemens.de',
    district: 'Altastenberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'nordhang-jause',
    name: 'Nordhang Jause Winterberg',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    additionalCategories: [{ category: 'Gastronomie', subcategory: 'Skihütten' }],
    description: 'Urige Hütte in Wintersportgebiet direkt am Skilift mit gutbürgerlicher deutscher Küche und Sonnenterrasse.',
    address: 'In d. Renau 11, 59955 Winterberg',
    phone: '02981 8996399',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'hotel-altastenberg',
    name: 'Hotel Altastenberg',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Hotels',
    description: '',
    address: 'Astenstraße 5, 59955 Winterberg-Altastenberg', // Guessing address since not in image, can be edited later
    district: 'Altastenberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'alm-salettl',
    name: 'Skihütte und Schirmbar Alm Salettl',
    category: 'Gastronomie',
    subcategory: 'Skihütten',
    description: '',
    address: 'Remmeswiese 10, 59955 Winterberg',
    website: 'https://wiesenwirt.de',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'brabander-skihutte',
    name: 'Skihütte Der Brabander',
    category: 'Gastronomie',
    subcategory: 'Skihütten',
    description: '',
    address: 'Am Waltenberg 69, 59955 Winterberg',
    phone: '02981 9320',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'quicks-skihutte',
    name: 'Quick\'s Skihütte',
    category: 'Gastronomie',
    subcategory: 'Skihütten',
    description: 'Skihütte mit gutbürgerlicher Küche, Snacks, Suppen, selbstgebackenen Kuchen und großem Außenbereich.',
    address: 'In d. Büre 42, 59955 Winterberg',
    phone: '02981 4253833',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'rauher-busch',
    name: 'Skihütte Rauher Busch',
    category: 'Gastronomie',
    subcategory: 'Skihütten',
    description: 'Gemütliche, rustikale Skihütte mit warmen und kalten deutschen Buffetspeisen sowie Bier vom Fass und Kaffee.',
    address: 'Remmeswiese 10, 59955 Winterberg',
    phone: '02981 3249',
    website: 'https://wiesenwirt.de',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'bei-moppi',
    name: 'Bei Möppi',
    category: 'Gastronomie',
    subcategory: 'Skihütten',
    description: '',
    address: 'In d. Büre 32, 59955 Winterberg',
    phone: '02981 1073',
    district: 'Winterberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'schirmbar-postwiese',
    name: 'Schirmbar Postwiese',
    category: 'Gastronomie',
    subcategory: 'Skihütten',
    description: '',
    address: 'Neuastenberger Str. 49, 59955 Winterberg-Neuastenberg',
    district: 'Neuastenberg',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'escape-room-winterberg',
    name: 'Escape Room Winterberg',
    category: 'Freizeit',
    subcategory: 'Indoor-Spielplätze',
    description: 'Escape-Room-Zentrum in Winterberg-Altastenberg. Spannende Rätselräume wie „Max Verschwinden“ und „Lost in Paradise“ für Teams, Familien und Gruppen.',
    address: 'Renauweg 34, 59955 Winterberg',
    district: 'Altastenberg',
    phone: '01516 4974348',
    website: 'https://escaperoomwinterberg.de',
    imageFallback: 'ER',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'foxx-club-winterberg',
    name: 'Foxx Club Winterberg',
    category: 'Freizeit',
    subcategory: 'Indoor-Spielplätze',
    description: 'Moderner Indoorspielplatz im Resort Schöner Asten in Altastenberg mit Kletteranlagen, Trampolinen, Röhrenrutschen und Spielspaß für Kinder.',
    address: 'Renauweg 54, 59955 Winterberg',
    district: 'Altastenberg',
    phone: '02981 8050',
    email: 'info@foxx-club.de',
    website: 'https://www.foxx-club.de',
    imageFallback: 'FC',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'monkey-island-winterberg',
    name: 'Monkey Island Winterberg',
    category: 'Freizeit',
    subcategory: 'Indoor-Spielplätze',
    description: 'Großer Indoorspielplatz und Familien-Erlebniswelt in Winterberg mit Klettervulkan, Trampolinen, Karussell, Funpark und Kleinkinderbereich.',
    address: 'Im Mühlengrund 25, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 5519717',
    email: 'info@monkey-island-winterberg.de',
    website: 'https://monkey-island-winterberg.de',
    imageFallback: 'MI',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'fun-fitness-24-winterberg',
    name: 'Fun Fitness 24 Winterberg',
    category: 'Freizeit',
    subcategory: 'Fitnessstudios',
    description: 'Modernes 24/7 Fitnessstudio in Winterberg. Rund um die Uhr geöffnet für Gerätetraining, Ausdauer, Freihantelbereich, Ernährungsberatung und Personal Training.',
    address: 'Am Waltenberg 49, 59955 Winterberg',
    district: 'Winterberg',
    phone: '0178 8538257',
    website: 'https://funfitness24.de',
    services: ['24/7 geöffnet', 'Gerätetraining', 'Freihantelbereich', 'Ernährungsberatung', 'Personal Training'],
    imageFallback: 'FF',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'corpus-pro-winterberg',
    name: 'corpus pro Winterberg',
    category: 'Freizeit',
    subcategory: 'Fitnessstudios',
    description: 'Fitness- und Gesundheitsstudio in Winterberg mit hochmodernen Matrix-Geräten, Freihantel- und Cardiobereich, Ernährungsberatung und individuellem Personal Training.',
    address: 'Am Hagenblech 73, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9199837',
    website: 'https://corpus-pro.com',
    services: ['Kraft- & Cardiotraining', 'Matrix Geräte', 'Ernährungsberatung', 'Personal Training', 'Lange Öffnungszeiten'],
    imageFallback: 'CP',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'koerperformen-winterberg',
    name: 'Körperformen EMS Training Winterberg',
    category: 'Freizeit',
    subcategory: 'Fitnessstudios',
    description: 'Effektives EMS-Ganzkörpertraining in nur 20 Minuten pro Woche mit persönlichem Trainer im Zentrum von Winterberg.',
    address: 'Hauptstraße 8, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9022444',
    email: 'winterberg@kformen.com',
    website: 'https://www.koerperformen-hsk.de',
    services: ['EMS-Training', 'Personal Training', 'Rückentraining', 'Gewichtsreduktion', 'Körperstraffung'],
    imageFallback: 'KF',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'fitnessclub-niedersfeld',
    name: 'Fitnessclub Niedersfeld e.V.',
    category: 'Freizeit',
    subcategory: 'Fitnessstudios',
    description: 'Gemeinnütziger Fitnessverein in Winterberg-Niedersfeld mit modernem Kraft- und Ausdauerbereich, Kursangeboten und familiärer Atmosphäre.',
    address: 'Alter Schulweg 10, 59955 Winterberg-Niedersfeld',
    district: 'Niedersfeld',
    phone: '01511 6303669',
    email: 'info@fitnessclub-niedersfeld.de',
    website: 'https://www.fitnessclub-niedersfeld.de',
    services: ['Krafttraining', 'Ausdauertraining', 'Fitnesskurse', 'Vereinssport'],
    imageFallback: 'FN',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'hotel-herrloh',
    name: 'Hotel Herrloh',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Hotels',
    description: 'Gemütliches 3-Sterne-Hotel direkt am Fuße des Herrloh und der St. Georg Sprungschanze in Winterberg. Ideale Lage für Skifahrer, Wanderer und Aktivurlauber mit Restaurant und Sonnenterrasse.',
    address: 'Herrlohweg 3, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92470',
    email: 'info@hotelherrloh.nl',
    website: 'https://www.hotelherrloh.nl',
    services: ['Direkt am Skigebiet / Lift', 'Restaurant & Bar', 'Sonnenterrasse', 'WLAN inklusive', 'Skikeller & Fahrradraum', 'Kostenlose Parkplätze'],
    imageFallback: 'HH',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'cafe-extrablatt-winterberg',
    name: 'Cafe Extrablatt Winterberg',
    category: 'Gastronomie',
    subcategory: 'Cafés',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Restaurant' },
      { category: 'Gastronomie', subcategory: 'Kneipen und Bars' }
    ],
    description: 'Beliebtes Café & Restaurant im Herzen von Winterberg an der Unteren Pforte mit großer Sonnenterrasse, täglichem großem Frühstücksbuffet, Burgern, Pizza, Cocktails und Kaffeespezialitäten.',
    address: 'Untere Pforte 4, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 8995180',
    website: 'https://cafe-extrablatt.de/standorte/details/winterberg',
    services: ['Tägliches Frühstücksbuffet', 'Sonnenterrasse', 'Cocktails & Bar', 'Speisen vor Ort & zum Mitnehmen', 'Zentrale Lage'],
    imageFallback: 'CE',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'markt-alm-winterberg',
    name: 'Markt Alm Winterberg',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Cafés' },
      { category: 'Gastronomie', subcategory: 'Kneipen und Bars' }
    ],
    description: 'Gemütliche Alm-Gastronomie im Lodge Hotel am Waltenberg. Bietet morgens ein reichhaltiges Alm-Frühstücksbuffet und tagsüber herzhafte alpenländische Spezialitäten und Sauerländer Klassiker.',
    address: 'Am Waltenberg 33, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9296970',
    website: 'https://marktalm.de',
    services: ['Alm-Frühstücksbuffet (ab 07:30)', 'Alpenländische Küche', 'Speisen vor Ort', 'Zentral am Waltenberg'],
    imageFallback: 'MA',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'bowlhaus-winterberg',
    name: 'Bowlhaus Winterberg',
    category: 'Freizeit',
    subcategory: 'Bowling',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Restaurant' },
      { category: 'Gastronomie', subcategory: 'Kneipen und Bars' }
    ],
    description: 'Modernes Bowling- und Freizeitzentrum in Winterberg mit 8 wettkampftauglichen Bowlingbahnen, samstags Disco-Bowling, Billardtischen, Darts, Airhockey sowie Restaurantbereich mit Burgern, Snacks und Drinks.',
    address: 'Orkestraße 2, 59955 Winterberg',
    district: 'Winterberg',
    phone: '0162 8464089',
    website: 'http://www.bowling-winterberg.de',
    services: ['8 Bowlingbahnen', 'Disco-Bowling jeden Samstag', 'Billard & Darts', 'Restaurant & Burger', 'Cocktails & Drinks', 'Events & Kindergeburtstage'],
    imageFallback: 'BW',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '15:00 - 23:00',
      tuesday: '15:00 - 23:00',
      wednesday: '15:00 - 23:00',
      thursday: '15:00 - 23:00',
      friday: '15:00 - 01:00',
      saturday: '14:00 - 01:00',
      sunday: '14:00 - 22:00'
    }
  },
  {
    id: 'landhotel-gasthof-zur-post',
    name: 'Landhotel Gasthof zur Post',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Hotels',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Restaurant' }
    ],
    description: 'Traditionsreiches, gemütliches Landhotel und Gasthof in Winterberg-Langewiese. Sauerländische Gastlichkeit, komfortable Zimmer und idealer Ausgangspunkt für Wanderer (Rothaarsteig) und Wintersportler.',
    address: 'Bundesstraße 20, 59955 Winterberg-Langewiese',
    district: 'Langewiese',
    phone: '02758 98430',
    services: ['Hotelzimmer', 'Gasthof & Restaurant', 'Wanderfreundlich (Rothaarsteig)', 'Parkplätze', 'Sonnenterrasse'],
    imageFallback: 'LP',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'landgasthof-gilsbach',
    name: 'Landgasthof Gilsbach',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Hotels',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Restaurant' }
    ],
    description: 'Familiengeführter 3-Sterne-Landgasthof in Winterberg-Langewiese mit gemütlichen Zimmern, regionaler Sauerländer Frischeküche, herrlicher Aussicht und direktem Einstieg in Wanderwege und Loipen.',
    address: 'Bundesstraße 25, 59955 Winterberg-Langewiese',
    district: 'Langewiese',
    phone: '02758 98420',
    website: 'https://www.landgasthof-gilsbach.de',
    services: ['3-Sterne-Hotel', 'Sauerländer Restaurant', 'Garten & Liegewiese', 'Wander- & Skigebiet-Nähe', 'WLAN & Parkplätze'],
    imageFallback: 'LG',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'haus-berchstein',
    name: 'Haus BerchStein',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Ferienhäuser',
    description: 'Großes, modernes Gruppen-Ferienhaus in Winterberg-Langewiese für bis zu 25 Personen mit 11 Schlafzimmern, 8 Bädern, großem Gemeinschaftsbereich, Garten und Panoramablick – ideal für Familien, Freundesgruppen und Seminare.',
    address: 'Grenzweg 8, 59955 Winterberg-Langewiese',
    district: 'Langewiese',
    phone: '0151 64688589',
    email: 'info@hausberchstein.de',
    website: 'https://hausberchstein.de',
    services: ['Gruppenhaus bis 25 Personen', '11 Schlafzimmer & 8 Bäder', 'Voll ausgestattete Küche', 'Garten & Grillbereich', 'WLAN inklusive'],
    imageFallback: 'HB',
    isPremium: false,
    status: 'approved'
  },
  {
    id: 'friseursalon-farbspiel-langewiese',
    name: 'Friseursalon Farbspiel Inh. Sabrina Gerke',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Moderner Friseursalon in Langewiese. Professionelle Schnitttechniken, Farbveredelungen, Balayage, Dauerwellen, Flecht- und Hochsteckfrisuren sowie Augenbrauen- und Wimpernpflege.',
    address: 'Bundesstraße 28, 59955 Winterberg-Langewiese',
    district: 'Langewiese',
    phone: '02758 2013023',
    website: 'https://ix.shore.com/bookings/salon-farbspiel-langewiese/locations',
    services: ['Damen-, Herren- & Kinderschnitte', 'Balayage & Strähnen', 'Haarfärbung & Tönung', 'Dauerwellen', 'Augenbrauen zupfen / färben'],
    imageFallback: 'FS',
    isPremium: false,
    status: 'approved',
    openingHours: {
      tuesday: '08:00 - 18:00',
      wednesday: '08:00 - 18:00',
      thursday: '08:00 - 18:00',
      friday: '08:00 - 18:00',
      saturday: '08:00 - 13:00',
      sunday: 'Geschlossen',
      monday: 'Geschlossen'
    }
  },
  {
    id: 'salon-farbspiel-siedlinghausen',
    name: 'Salon Farbspiel Inh. Sabrina Gerke',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Ihr Wohlfühl-Friseursalon in Winterberg-Siedlinghausen für typgerechte Haarschnitte, brillante Colorationen, Styling und Haarpflege in entspannter Atmosphäre.',
    address: 'Im Schling 20, 59955 Winterberg-Siedlinghausen',
    district: 'Siedlinghausen',
    phone: '02983 970610',
    services: ['Haarschnitte & Styling', 'Farb- & Strähnentechniken', 'Individuelle Typberatung', 'Haarpflege & Kuren'],
    imageFallback: 'SF',
    isPremium: false,
    status: 'approved',
    openingHours: {
      tuesday: '09:00 - 18:00',
      wednesday: '09:00 - 18:00',
      thursday: '09:00 - 18:00',
      friday: '09:00 - 18:00',
      saturday: '08:00 - 13:00',
      sunday: 'Geschlossen',
      monday: 'Geschlossen'
    }
  },
  {
    id: 'standpunkt-verlag',
    name: 'Standpunkt-Verlag GmbH',
    category: 'Dienstleistungen',
    subcategory: 'Marketingdienstleistungen',
    description: 'Regionaler Verlag und Medienagentur in Winterberg-Siedlinghausen. Herausgeber von hochwertigen Regional- und Lifestylemagazinen (u. a. Woll-Magazin, Heimatliebe), Printmedien, Redaktion und Marketingdienstleistungen.',
    address: 'Hochsauerlandstraße 13, 59955 Winterberg-Siedlinghausen',
    district: 'Siedlinghausen',
    phone: '02983 979960',
    website: 'https://www.standpunktverlag.de',
    services: ['Verlagswesen & Print', 'Regionalmagazine', 'Redaktion & Content', 'Werbeanzeigen & Marketing', 'Grafikdesign & Layout'],
    imageFallback: 'SV',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '08:00 - 17:00',
      tuesday: '08:00 - 17:00',
      wednesday: '08:00 - 17:00',
      thursday: '08:00 - 17:00',
      friday: '08:00 - 14:00',
      saturday: 'Geschlossen',
      sunday: 'Geschlossen'
    }
  },
  {
    id: 'baeckerei-gerke-langewiese',
    name: 'Bäckerei Gerke (Franzes)',
    category: 'Handwerk',
    subcategory: 'Bäckerei',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Cafés' },
      { category: 'Einzelhandel', subcategory: 'Supermarkt' }
    ],
    description: 'Traditionelle Handwerksbäckerei und gemütlicher Dorfladen in Winterberg-Langewiese. Frische Brötchen, handwerklich gebackene Brote, Kuchen, Kaffeespezialitäten sowie Lebensmittel des täglichen Bedarfs.',
    address: 'Bundesstraße 19, 59955 Winterberg-Langewiese',
    district: 'Langewiese',
    phone: '02758 280',
    email: 'baeckereigerke@freenet.de',
    services: ['Handwerksbrote & Brötchen', 'Kuchen & Gebäck', 'Kaffee to go & belegte Brötchen', 'Lebensmittel / Dorfladen', 'Frühstücksversorgung'],
    imageFallback: 'BG',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '06:30 - 12:30',
      tuesday: '06:30 - 12:30',
      wednesday: '06:30 - 12:30',
      thursday: '06:30 - 12:30',
      friday: '06:30 - 12:30',
      saturday: '06:30 - 12:00',
      sunday: '08:00 - 11:00'
    }
  },
  {
    id: 'tinq-tankautomat-langewiese',
    name: 'TinQ 24h-Tankautomat Langewiese',
    category: 'Einzelhandel',
    subcategory: 'Tankstellen',
    additionalCategories: [
      { category: 'Handwerk', subcategory: 'KFZ-Werkstätten' }
    ],
    description: 'Moderne 24-Stunden-Automatentankstelle an der Bundesstraße in Winterberg-Langewiese für PKW und LKW mit EC-, Kreditkarten- und Flottenkarten-Zahlung.',
    address: 'Bundesstraße 38, 59955 Winterberg-Langewiese',
    district: 'Langewiese',
    phone: '02758 287',
    website: 'https://gulf.de',
    services: ['24/7 Tankautomat', 'Super E10, Super E5 & Diesel', 'Kartenzahlung (EC / Kreditkarte / Flottenkarte)', 'Direkt an der B236'],
    imageFallback: 'TQ',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '00:00 - 24:00',
      tuesday: '00:00 - 24:00',
      wednesday: '00:00 - 24:00',
      thursday: '00:00 - 24:00',
      friday: '00:00 - 24:00',
      saturday: '00:00 - 24:00',
      sunday: '00:00 - 24:00'
    }
  },
  {
    id: 'jet-tankstelle-winterberg',
    name: 'JET Tankstelle Winterberg',
    category: 'Einzelhandel',
    subcategory: 'Tankstellen',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Imbisse' },
      { category: 'Handwerk', subcategory: 'KFZ-Werkstätten' }
    ],
    description: 'JET Marken-Tankstelle in Winterberg mit günstigen Kraftstoffen, modernem Shop, Bistro-Snacks (belegte Baguettes, Bockwurst, Frikadellen, Coffee to Go), Crushed Ice, Autopflege und SB-Waschanlage.',
    address: 'Lamfert 1, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9298634',
    website: 'https://www.jet.de/tankstellen/winterberg/lamfert-1',
    services: ['Markenkraftstoffe günstig', 'Bistro & Coffee to Go', 'Snacks & Belegte Baguettes', 'Tankstellen-Shop', 'Crushed Ice & Autozubehör'],
    imageFallback: 'JT',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '06:00 - 23:00',
      tuesday: '06:00 - 23:00',
      wednesday: '06:00 - 23:00',
      thursday: '06:00 - 23:00',
      friday: '06:00 - 23:00',
      saturday: '07:00 - 23:00',
      sunday: '08:00 - 23:00'
    }
  },
  {
    id: 'aral-tankstelle-winterberg',
    name: 'Aral Tankstelle Winterberg',
    category: 'Einzelhandel',
    subcategory: 'Tankstellen',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Imbisse' },
      { category: 'Handwerk', subcategory: 'KFZ-Werkstätten' }
    ],
    description: 'Aral Tankstelle in Winterberg Am Hagenblech. 24/7 geöffnet mit Aral Kraftstoffen inklusive Ultimate, REWE To Go Shop, PetitBistro mit frischen Snacks, Kaffeespezialitäten, LKW-Diesel und Waschanlage.',
    address: 'Am Hagenblech 60, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92600',
    website: 'https://tankstelle.aral.de/winterberg/am-hagenblech-60/14164700',
    services: ['24/7 geöffnet', 'Aral Ultimate Kraftstoffe', 'REWE To Go Shop', 'PetitBistro & Kaffee', 'Waschanlage', 'LKW-Diesel'],
    imageFallback: 'AR',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '00:00 - 24:00',
      tuesday: '00:00 - 24:00',
      wednesday: '00:00 - 24:00',
      thursday: '00:00 - 24:00',
      friday: '00:00 - 24:00',
      saturday: '00:00 - 24:00',
      sunday: '00:00 - 24:00'
    }
  },
  {
    id: 'calpam-tankautomat-zueschen',
    name: 'Calpam Tankautomat Züschen',
    category: 'Einzelhandel',
    subcategory: 'Tankstellen',
    additionalCategories: [
      { category: 'Handwerk', subcategory: 'KFZ-Werkstätten' }
    ],
    description: '24-Stunden-Automatentankstelle von Calpam in Winterberg-Züschen. Schnelles und unkompliziertes Tanken rund um die Uhr mit EC- und Tankkarten an der Nuhnetalstraße.',
    address: 'Nuhnetalstraße 88, 59955 Winterberg-Züschen',
    district: 'Züschen',
    phone: '02981 908301',
    website: 'https://calpam.com',
    services: ['24/7 Tankautomat', 'Super E10, Super E5 & Diesel', 'Kartenzahlung (EC / Flottenkarten)', 'Direkt an der B236 in Züschen'],
    imageFallback: 'CP',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '00:00 - 24:00',
      tuesday: '00:00 - 24:00',
      wednesday: '00:00 - 24:00',
      thursday: '00:00 - 24:00',
      friday: '00:00 - 24:00',
      saturday: '00:00 - 24:00',
      sunday: '00:00 - 24:00'
    }
  },
  {
    id: 'baeckerei-isken-am-waltenberg',
    name: 'Bäckerei Cafe Isken (Am Waltenberg)',
    category: 'Handwerk',
    subcategory: 'Bäckerei',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Cafés' }
    ],
    description: 'Beliebtes Bäckerei-Café der Bäckerei Isken im Herzen von Winterberg an der Flaniermeile Am Waltenberg. Großes Frühstücksangebot, Kaffeespezialitäten, frische Handwerksbrötchen, Brote und feine Torten.',
    address: 'Am Waltenberg 11, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9292933',
    website: 'https://www.baeckerei-isken.de',
    services: ['Frühstück & Brunch', 'Kaffeespezialitäten', 'Handwerksbrot & Brötchen', 'Kuchen & Torten', 'Sitzplätze innen & außen'],
    imageFallback: 'BI',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '06:30 - 18:00',
      tuesday: '06:30 - 18:00',
      wednesday: '06:30 - 18:00',
      thursday: '06:30 - 18:00',
      friday: '06:30 - 18:00',
      saturday: '06:30 - 18:00',
      sunday: '06:30 - 18:00'
    }
  },
  {
    id: 'baeckerei-gerke-hauptstrasse',
    name: 'Bäckerei Gerke (Hauptstraße)',
    category: 'Handwerk',
    subcategory: 'Bäckerei',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Cafés' }
    ],
    description: 'Traditionelle Handwerksbäckerei in der Winterberger Innenstadt. Knusprige Brötchen, traditionelle Sauerländer Natursauerteigbrote, Gebäck und Snacks.',
    address: 'Hauptstraße 21, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 802867',
    services: ['Traditionelle Handwerksbrote', 'Frische Brötchen', 'Snacks & Kaffee to go', 'Kuchen & Gebäck'],
    imageFallback: 'BG',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '06:30 - 18:00',
      tuesday: '06:30 - 18:00',
      wednesday: '06:30 - 18:00',
      thursday: '06:30 - 18:00',
      friday: '06:30 - 18:00',
      saturday: '06:30 - 13:00',
      sunday: '07:30 - 11:30'
    }
  },
  {
    id: 'cafe-engemann-winterberg',
    name: 'Cafe Engemann',
    category: 'Gastronomie',
    subcategory: 'Cafés',
    additionalCategories: [
      { category: 'Handwerk', subcategory: 'Bäckerei' }
    ],
    description: 'Traditionsreiches Konditorei-Café am Waltenberg in Winterberg. Bekannt für hausgemachte Torten, handgefertigte Pralinen, feines Gebäck und gemütliche Frühstücksangebote.',
    address: 'Am Waltenberg 14, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://www.cafe-engemann-winterberg.de',
    services: ['Konditorei & Torten', 'Hausgemachte Pralinen', 'Frühstück & Kaffeespezialitäten', 'Große Kuchentheke', 'Gemütliches Café'],
    imageFallback: 'CE',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '08:00 - 18:00',
      tuesday: '08:00 - 18:00',
      wednesday: '08:00 - 18:00',
      thursday: '08:00 - 18:00',
      friday: '08:00 - 18:00',
      saturday: '08:00 - 18:00',
      sunday: '08:00 - 18:00'
    }
  },
  {
    id: 'landbaeckerei-sommer-winterberg',
    name: 'Landbäckerei Sommer GmbH',
    category: 'Handwerk',
    subcategory: 'Bäckerei',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Cafés' }
    ],
    description: 'Filiale der Landbäckerei Sommer in der Neuen Mitte Winterberg. Frische Brote, Brötchenvielfalt, Snacks, belegte Brötchen und Kaffeespezialitäten für unterwegs oder zum Verweilen.',
    address: 'Neue Mitte 4, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 802805',
    website: 'https://www.landbaeckerei-sommer.de',
    services: ['Frische Backwaren', 'Snacks & Belegte Brötchen', 'Kaffeespezialitäten', 'Café-Sitzbereich'],
    imageFallback: 'LS',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '07:00 - 18:00',
      tuesday: '07:00 - 18:00',
      wednesday: '07:00 - 18:00',
      thursday: '07:00 - 18:00',
      friday: '07:00 - 18:00',
      saturday: '07:00 - 16:00',
      sunday: '07:30 - 12:00'
    }
  },
  {
    id: 'baeckerei-isken-rewe-winterberg',
    name: 'Bäckerei Isken im REWE',
    category: 'Handwerk',
    subcategory: 'Bäckerei',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Cafés' },
      { category: 'Einzelhandel', subcategory: 'Supermarkt' }
    ],
    description: 'Bäckerei- und Caféfiliale von Isken im REWE Center an der Poststraße in Winterberg. Frische Backwaren, Frühstückssnacks, belegte Brötchen und Kaffeespezialitäten mit gemütlichem Sitzbereich.',
    address: 'Poststraße 6, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 8998245',
    website: 'https://baeckerei-isken.de',
    services: ['Frische Backwaren täglich', 'Snacks & belegte Brötchen', 'Kaffee & Heißgetränke', 'Gemütlicher Sitzbereich'],
    imageFallback: 'IR',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '07:00 - 20:00',
      tuesday: '07:00 - 20:00',
      wednesday: '07:00 - 20:00',
      thursday: '07:00 - 20:00',
      friday: '07:00 - 20:00',
      saturday: '07:00 - 20:00',
      sunday: '07:00 - 11:30'
    }
  },
  {
    id: 'baeckerei-isken-niedersfeld',
    name: 'Bäckerei Peter Isken GmbH (Niedersfeld)',
    category: 'Handwerk',
    subcategory: 'Bäckerei',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Cafés' }
    ],
    description: 'Hauptsitz und traditionsreiches Bäckerei-Café der Bäckerei Isken in Winterberg-Niedersfeld. Hochwertiges Handwerksbrot, feine Torten, Chocolaterie, großes Frühstücks- und Caféangebot.',
    address: 'Ruhrstraße 21, 59955 Winterberg-Niedersfeld',
    district: 'Niedersfeld',
    phone: '02985 908650',
    website: 'https://baeckerei-isken.de',
    services: ['Handwerksbäckerei & Konditorei', 'Chocolaterie', 'Großes Café & Frühstück', 'Torten & Feinbackwaren', 'Sonnenterrasse'],
    imageFallback: 'PI',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '06:00 - 18:00',
      tuesday: '06:00 - 18:00',
      wednesday: '06:00 - 18:00',
      thursday: '06:00 - 18:00',
      friday: '06:00 - 18:00',
      saturday: '06:00 - 17:00',
      sunday: '07:00 - 17:00'
    }
  },
  {
    id: 'cafe-kraemer-winterberg',
    name: 'Café Krämer',
    category: 'Gastronomie',
    subcategory: 'Cafés',
    additionalCategories: [
      { category: 'Handwerk', subcategory: 'Bäckerei' }
    ],
    description: 'Gemütliches Bäckerei-Café und Konditorei an der Hagenstraße im Zentrum von Winterberg. Frische Brot- und Brötchenspezialitäten, handgemachte Torten, Kuchen und leckeres Frühstück.',
    address: 'Hagenstraße 1, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 523',
    website: 'https://cafe-kraemer.de',
    services: ['Frühstücksangebote', 'Hausgemachte Torten & Kuchen', 'Handwerksbackwaren', 'Kaffeespezialitäten', 'Café-Sitzbereich'],
    imageFallback: 'CK',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '06:30 - 18:00',
      tuesday: '06:30 - 18:00',
      wednesday: '06:30 - 18:00',
      thursday: '06:30 - 18:00',
      friday: '06:30 - 18:00',
      saturday: '06:30 - 18:00',
      sunday: '09:30 - 18:00'
    }
  },
  {
    id: 'tismes-baeckerei-neuastenberg',
    name: 'Tismes Bäckerei | Café (Neuastenberg)',
    category: 'Handwerk',
    subcategory: 'Bäckerei',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Cafés' }
    ],
    description: 'Gemütliche Bäckerei & Café in Winterberg-Neuastenberg an der Winterberger Straße. Frische Brötchen, handwerkliche Brote, Gebäck, Frühstück und Kaffee für Urlauber, Skifahrer und Einheimische.',
    address: 'Winterberger Str. 11, 59955 Winterberg-Neuastenberg',
    district: 'Neuastenberg',
    phone: '0160 91263683',
    website: 'https://www.tismes.de',
    services: ['Handwerksbrötchen & Brote', 'Kuchen & Teilchen', 'Frühstück & Kaffee', 'Café-Sitzplätze'],
    imageFallback: 'TB',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '07:30 - 12:30',
      tuesday: '07:30 - 12:30',
      wednesday: '07:30 - 12:30',
      thursday: '07:30 - 12:30',
      friday: '07:30 - 12:30',
      saturday: '07:30 - 12:30',
      sunday: '07:30 - 11:30'
    }
  },
  {
    id: 'tismes-baeckerei-siedlinghausen',
    name: 'Tismes Bäckerei Café (Siedlinghausen)',
    category: 'Handwerk',
    subcategory: 'Bäckerei',
    additionalCategories: [
      { category: 'Gastronomie', subcategory: 'Cafés' }
    ],
    description: 'Traditionelle Familienbäckerei und gemütliches Café in Winterberg-Siedlinghausen an der Kahlenbergstraße. Meisterhafte Handwerksbackwaren, Kuchen, Torten, Frühstück und Kaffeespezialitäten.',
    address: 'Kahlenbergstraße 1, 59955 Winterberg-Siedlinghausen',
    district: 'Siedlinghausen',
    phone: '02983 9705665',
    website: 'https://www.tismes.de',
    services: ['Handwerksbäckerei & Konditorei', 'Großes Café & Frühstück', 'Torten & Kuchen', 'Kaffeespezialitäten', 'Frische Brötchen täglich'],
    imageFallback: 'TS',
    isPremium: false,
    status: 'approved',
    openingHours: {
      monday: '06:00 - 18:00',
      tuesday: '06:00 - 18:00',
      wednesday: '06:00 - 18:00',
      thursday: '06:00 - 18:00',
      friday: '06:00 - 18:00',
      saturday: '06:00 - 12:30',
      sunday: '07:30 - 11:30'
    }
  }

];

export const themes: Record<ThemeKey, ThemeConfig> = {
  nature: {
    name: 'Klassisch Natur',
    description: 'Erdige Grüntöne mit modernen orangefarbenen Akzenten.',
    bgPage: 'bg-stone-50',
    textBase: 'text-stone-900',
    textMuted: 'text-stone-500',
    primaryBtn: 'bg-orange-500 hover:bg-orange-600 text-white shadow-lg shadow-orange-500/30 transition-all',
    categoryTagActive: 'bg-gradient-to-r from-orange-400 to-orange-500 text-white shadow-md shadow-orange-500/20',
    categoryTagInactive: 'bg-white/40 text-stone-700 hover:bg-white/70 hover:text-orange-600 backdrop-blur-md border border-white/50 transition-colors',
    cardBg: 'bg-white/60 backdrop-blur-xl',
    cardBorder: 'border-white/60 hover:border-orange-200 transition-colors',
    cardShadow: 'shadow-[0_8px_30px_rgb(0,0,0,0.04)]',
    iconAccent: 'text-orange-500',
    headerBg: 'bg-emerald-900/95 backdrop-blur-md text-stone-50',
    bottomRightImage: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=1600&auto=format&fit=crop',
  },
  winter: {
    name: 'Winterzauber',
    description: 'Kühle, kristalline Blautöne, passend zur Wintersport-Metropole.',
    bgPage: 'bg-slate-50',
    textBase: 'text-slate-900',
    textMuted: 'text-slate-500',
    primaryBtn: 'bg-sky-600 hover:bg-sky-700 text-white',
    categoryTagActive: 'bg-sky-600 text-white',
    categoryTagInactive: 'bg-slate-200 text-slate-700 hover:bg-slate-300',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-100/50',
    cardShadow: 'shadow-md shadow-slate-200/50',
    iconAccent: 'text-sky-500',
    headerBg: 'bg-white text-slate-900 border-b border-slate-200',
  },
  modern: {
    name: 'Modern Business',
    description: 'Klarer Kontrast, schlichtes Design und professioneller Fokus.',
    bgPage: 'bg-neutral-100',
    textBase: 'text-neutral-900',
    textMuted: 'text-neutral-500',
    primaryBtn: 'bg-black hover:bg-neutral-800 text-white rounded-none',
    categoryTagActive: 'bg-black text-white rounded-none',
    categoryTagInactive: 'bg-neutral-200 text-neutral-800 hover:bg-neutral-300 rounded-none',
    cardBg: 'bg-white rounded-none',
    cardBorder: 'border-neutral-300 rounded-none',
    cardShadow: '',
    iconAccent: 'text-neutral-900',
    headerBg: 'bg-black text-white',
  },
  alpine: {
    name: 'Gemütlich Alpin',
    description: 'Warme Farben und sanfte Kontraste für rustikale Gemütlichkeit.',
    bgPage: 'bg-orange-50',
    textBase: 'text-stone-900',
    textMuted: 'text-stone-600',
    primaryBtn: 'bg-orange-700 hover:bg-orange-800 text-white',
    categoryTagActive: 'bg-orange-700 text-white',
    categoryTagInactive: 'bg-orange-200/50 text-orange-900 hover:bg-orange-200',
    cardBg: 'bg-amber-50/50',
    cardBorder: 'border-orange-200/60',
    cardShadow: 'shadow-sm',
    iconAccent: 'text-orange-600',
    headerBg: 'bg-orange-100 text-orange-950 border-b border-orange-200',
  },
  panorama: {
    name: 'Panorama Blur',
    description: 'Vollflächiges Hintergrundbild mit leichtem Blur, für maximale Atmosphäre.',
    bgPage: 'bg-slate-900',
    textBase: 'text-slate-100',
    textMuted: 'text-slate-300',
    primaryBtn: 'bg-emerald-600 hover:bg-emerald-700 text-white',
    categoryTagActive: 'bg-emerald-600 text-white',
    categoryTagInactive: 'bg-slate-800/60 text-slate-200 hover:bg-slate-700/60 backdrop-blur-md',
    cardBg: 'bg-slate-900/60 backdrop-blur-md',
    cardBorder: 'border-slate-700/50',
    cardShadow: 'shadow-xl',
    iconAccent: 'text-emerald-400',
    headerBg: 'bg-slate-900/80 backdrop-blur-lg border-b border-white/10',
    backgroundImage: 'https://images.unsplash.com/photo-1498860714247-49f9dfccafac?q=80&w=2000&auto=format&fit=crop', // Winterberg scenery
    backgroundBlur: 'blur-sm',
    backgroundOpacity: 'opacity-40',
  },
  glass: {
    name: 'Glassmorphism',
    description: 'Helles, durchlässiges Design mit einem dekorativen Natur-Element unten rechts.',
    bgPage: 'bg-emerald-50',
    textBase: 'text-emerald-950',
    textMuted: 'text-emerald-700/80',
    primaryBtn: 'bg-emerald-800 hover:bg-emerald-900 text-white',
    categoryTagActive: 'bg-emerald-800 text-white',
    categoryTagInactive: 'bg-white/40 text-emerald-900 hover:bg-white/60 backdrop-blur-md border border-white/50',
    cardBg: 'bg-white/60 backdrop-blur-xl',
    cardBorder: 'border-white/60',
    cardShadow: 'shadow-[0_8px_30px_rgb(0,0,0,0.04)]',
    iconAccent: 'text-emerald-700',
    headerBg: 'bg-white/40 backdrop-blur-xl border-b border-white/60',
    bottomRightImage: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=1600&auto=format&fit=crop', // Forest scenery
  },
  dark: {
    name: 'Dark Mode',
    description: 'Dunkles Farbschema für das gesamte Verzeichnis.',
    bgPage: 'bg-slate-900',
    textBase: 'text-slate-100',
    textMuted: 'text-slate-400',
    primaryBtn: 'bg-emerald-600 hover:bg-emerald-700 text-white',
    categoryTagActive: 'bg-emerald-600 text-white',
    categoryTagInactive: 'bg-slate-800 text-slate-300 hover:bg-slate-700 border border-slate-700',
    cardBg: 'bg-slate-800/80 backdrop-blur-md',
    cardBorder: 'border-slate-700',
    cardShadow: 'shadow-lg shadow-black/20',
    iconAccent: 'text-emerald-400',
    headerBg: 'bg-slate-950 border-b border-slate-800 text-slate-100',
  }
};

export const categories: CategoryGroup[] = [
  { name: 'Hotels und Unterkünfte', subcategories: ['Ferienparks', 'Ferienhäuser', 'Ferienwohnungen', 'Hotels'] },
  { name: 'Handwerk', subcategories: ['KFZ-Werkstätten', 'Schreinereien', 'Wäschereien', 'Dachdecker', 'Elektriker', 'Friseur', 'Bäckerei', 'Heizungstechnik', 'Bauunternehmen', 'Maler & Lackierer', 'Gartenbauer'] },
  { name: 'Einzelhandel', subcategories: ['Supermarkt', 'Tankstellen', 'Bekleidung', 'Bürobedarf', 'Autohäuser'] },
  { name: 'Gastronomie', subcategories: ['Restaurant', 'Cafés', 'Kneipen und Bars', 'Skihütten', 'Eisdielen', 'Pizzerien', 'Imbisse', 'Weinstuben'] },
  { name: 'Dienstleistungen', subcategories: ['Steuerberater', 'Marketingdienstleistungen', 'Finanzberatung', 'Rechtsanwälte', 'Banken', 'Versicherungsagenturen'] },
  { name: 'Freizeit', subcategories: ['Indoor-Spielplätze', 'Fitnessstudios', 'Bowling', 'Tennisplätze', 'Fußballvereine', 'Schwimmbäder', 'Outdoor-Freizeitgebiet'] }
];
