import { Business, ThemeConfig, ThemeKey, CategoryGroup } from './types';

export const businesses: Business[] = [
  {
    id: 'rewe-winterberg',
    name: 'REWE',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'Dein REWE Supermarkt in Winterberg.',
    address: 'Poststraße 6, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 7736',
    isPremium: false,
  },
  {
    id: '142',
    name: 'Hessenkeller Winterberg',
    category: 'Gastronomie',
    subcategory: 'Kneipen und Bars',
    description: 'Kneipe in Winterberg. Beliebter Treffpunkt mit Live-Veranstaltungen, Tanzen und Quizabenden.',
    address: 'Am Waltenberg 1, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 930111',
    website: 'https://hotel-hessenhof.de',
    imageFallback: 'HK',
  },
  {
    id: '143',
    name: 'Lingenauber',
    category: 'Gastronomie',
    subcategory: 'Kneipen und Bars',
    description: 'Gastrokneipe in Siedlinghausen. Bietet Sitzplätze im Freien und Hunde sind erlaubt.',
    address: 'Hochsauerlandstraße 15, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02983 8231',
    website: 'https://lingenaubers.de',
    imageFallback: 'LI',
  },
  {
    id: '144',
    name: 'Blackwater Irish Pub Winterberg',
    category: 'Gastronomie',
    subcategory: 'Kneipen und Bars',
    description: 'Beliebte Kneipe mit traditioneller Einrichtung, irischen Bieren vom Fass und Sport auf Großbildleinwand.',
    address: 'Nuhnestraße 2, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 899539',
    website: 'https://blackwater-irishpub.de',
    imageFallback: 'BW',
  },
  {
    id: '145',
    name: 'Bu\'ket Bar Winterberg',
    category: 'Gastronomie',
    subcategory: 'Kneipen und Bars',
    description: 'Cocktailbar in Winterberg. Hunde erlaubt.',
    address: 'Poststraße 1, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 8968670',
    imageFallback: 'BK',
  },

  {
    id: '1',
    name: 'Car-Point Winterberg',
    category: 'Handwerk',
    subcategory: 'KFZ-Werkstätten',
    description: 'Wir sind Profis! Wir bieten KFZ-Reparaturen aller Art an.',
    address: 'Remmeswiese 30a, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://car-point-winterberg.de/',
    imageFallback: 'CP',
    isVerified: true,
    openingHours: {
      monday: '08:00 - 17:00',
      tuesday: '08:00 - 17:00',
      wednesday: '08:00 - 17:00',
      thursday: '08:00 - 17:00',
      friday: '08:00 - 15:00',
      saturday: 'Geschlossen',
      sunday: 'Geschlossen'
    }
  },
  {
    id: '2',
    name: 'Autoservice Kruk',
    category: 'Handwerk',
    subcategory: 'KFZ-Werkstätten',
    description: 'Ihre freundliche Autofachwerkstatt in Winterberg-Siedlinghausen. Schnell, Preiswert & Zuverlässig.',
    address: 'Hochsauerlandstraße 78a, 59955 Winterberg',
    district: 'Siedlinghausen',
    website: 'https://www.autoservice-kruk.de/',
    imageFallback: 'AK',
  },
  {
    id: 'nagel',
    name: 'Nagel Udo Autoreparatur',
    category: 'Handwerk',
    subcategory: 'KFZ-Werkstätten',
    description: 'AUTOREPARATUREN',
    address: 'Hochsauerlandstr. 56, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02983 7 61',
    imageFallback: 'NUA',
    isVerified: true
  },
  {
    id: '3',
    name: 'HAS-Antriebstechnik Bosch Car Service',
    category: 'Handwerk',
    subcategory: 'KFZ-Werkstätten',
    description: 'Bosch Car Service und Werkstatt Dienstleistungen für alle Fabrikate in Winterberg.',
    address: 'Am Hagenblech 38, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://has-antriebstechnik.de/',
    imageFallback: 'HAS',
  },
  {
    id: '4',
    name: 'Andreas Mantel Auto & Zweirad',
    category: 'Handwerk',
    subcategory: 'KFZ-Werkstätten',
    description: 'Ihr Meisterbetrieb für Auto & Zweirad in Winterberg.',
    address: 'Ruhrstraße 69, 59955 Winterberg',
    district: 'Niedersfeld',
    website: 'https://www.mantel-kfz.de/',
    imageFallback: 'AM',
  },
  {
    id: '5',
    name: 'Schürmann & Kruse OHG',
    category: 'Handwerk',
    subcategory: 'KFZ-Werkstätten',
    description: 'Zuverlässiger Service, markenübergreifende Expertise & höchste Präzision. High-End Upgrades, Engineering und Performance-Lösungen.',
    address: 'Am Hagenblech 85, 59955 Winterberg',
    district: 'Winterberg',
    phone: '+49 151 50 70 51 44',
    website: 'https://www.schuermann-kruse.de/',
    imageFallback: 'SK',
  },
  {
    id: '6',
    name: 'Erlebnisberg Kappe',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Bikepark, Sommerrodelbahn und Kletterwald - Spaß für die ganze Familie.',
    address: 'Kappestrasse 1, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://www.erlebnisbergkappe.de/',
    imageFallback: 'EK',
  },
  {
    id: '7',
    name: 'Bröker Objekteinrichtungen GmbH & Co. KG',
    category: 'Handwerk',
    subcategory: 'Schreinereien',
    description: 'Tischler NRW - Team Compact Handwerk mit Ideen!',
    address: 'Remmeswiese 26, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92965-0',
    website: 'https://broeker-winterberg.de/',
    imageFallback: 'BO',
  },
  {
    id: '8',
    name: 'Stockhausen Treppen GmbH',
    category: 'Handwerk',
    subcategory: 'Schreinereien',
    description: 'Stockhausen Treppen - Ihr Spezialist für individuellen Treppenbau.',
    address: 'Nuhnetalstraße 132, 59955 Winterberg',
    district: 'Züschen',
    phone: '02981 8969060',
    website: 'https://stockhausen-treppen.de/',
    imageFallback: 'ST',
  },
  {
    id: '9',
    name: 'Rudolf Ittermann',
    category: 'Handwerk',
    subcategory: 'Schreinereien',
    description: 'Rudolf Ittermann Tischlerei in Winterberg.',
    address: 'Am Eschenberg 8, 59955 Winterberg',
    district: 'Niedersfeld',
    phone: '02985 8100',
    imageFallback: 'RI',
  },
  {
    id: '10',
    name: 'Daniel Sögtrop Tischlerei',
    category: 'Handwerk',
    subcategory: 'Schreinereien',
    description: 'Daniel Sögtrop Tischlerei - Ihr Ansprechpartner für Holz und Möbel.',
    address: 'Hochsauerlandstr. 72, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02983 9740310',
    website: 'https://tischlerei-soegtrop.de/',
    imageFallback: 'DS',
  },
  {
    id: '11',
    name: 'Textilreinigung Roj',
    category: 'Handwerk',
    subcategory: 'Wäschereien',
    description: 'Ihre Reinigung in Winterberg für Änderungen, Bettdeckenreinigung, Biochemische Reinigung, Bügeln und Großwäscherei.',
    address: 'Hauptstraße 15, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 5080280',
    imageFallback: 'TR',
  },
  {
    id: '12',
    name: 'Müller Michael Elektroinstallation',
    category: 'Handwerk',
    subcategory: 'Elektriker',
    description: 'Elektroinstallationen und Fachbetrieb.',
    address: 'Poststr. 9, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 22 33',
    imageFallback: 'MM',
  },
  {
    id: '13',
    name: 'Quick Reiner Elektroinstallation',
    category: 'Handwerk',
    subcategory: 'Elektriker',
    description: 'Elektroinstallationen',
    address: 'Hellenstr. 54, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 24 64',
    imageFallback: 'QR',
  },
  {
    id: '14',
    name: 'Kösler Elektro',
    category: 'Handwerk',
    subcategory: 'Elektriker',
    description: 'Elektroinstallationen',
    address: 'Schanzenstr. 16, 59955 Winterberg',
    district: 'Winterberg',
    phone: '0173 5 17 71 51',
    imageFallback: 'KE',
  },
  {
    id: '15',
    name: 'Kiemen Hermann J. Elektroinstallation',
    category: 'Handwerk',
    subcategory: 'Elektriker',
    description: 'Elektroinstallationen',
    address: 'Briloner Str. 15, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02983 82 60',
    imageFallback: 'HK',
  },
  {
    id: '16',
    name: 'Meisterbetrieb Menke',
    category: 'Handwerk',
    subcategory: 'Dachdecker',
    description: 'Dachdecker Meisterbetrieb',
    address: 'Am Iberg 2, 59955 Winterberg',
    district: 'Silbach',
    phone: '02983 1404',
    website: 'mailto:info@meisterbetrieb-menke.de',
    imageFallback: 'MM',
  },
  {
    id: '17',
    name: 'Müllenhoff Winterberg Bedachungs GmbH',
    category: 'Handwerk',
    subcategory: 'Dachdecker',
    description: 'Bedachungen',
    address: 'Remmeswiese 1, 59955 Winterberg',
    district: 'Winterberg',
    phone: '+49 2981 472',
    imageFallback: 'MW',
  },
  {
    id: '18',
    name: 'Schindel Dachdeckermeister',
    category: 'Handwerk',
    subcategory: 'Dachdecker',
    description: 'Dachdeckermeister Schindel',
    address: 'Kirchstr. 13, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 8160938',
    website: 'mailto:info@ddm-schindel.de',
    imageFallback: 'SD',
  },
  {
    id: '19',
    name: 'Netto Marken-Discount',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'Lebensmittel, frische Backwaren, Obst und Gemüse.',
    address: 'Hochsauerlandstr. 60, 59955 Winterberg',
    district: 'Siedlinghausen',
    website: 'https://www.netto-online.de/',
    imageFallback: 'NM',
  },
  {
    id: '20',
    name: 'Netto Marken-Discount',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'Lebensmittel, frische Backwaren, Obst und Gemüse.',
    address: 'Ruhrstr. 4, 59955 Winterberg',
    district: 'Niedersfeld',
    website: 'https://www.netto-online.de/',
    imageFallback: 'NM',
  },
  {
    id: '21',
    name: 'Lidl',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'Beste Qualität zum niedrigen Preis.',
    address: 'Im Mühlengrund 1, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://www.lidl.de/',
    imageFallback: 'LI',
    openingHours: {
      monday: '07:00 - 21:00',
      tuesday: '07:00 - 21:00',
      wednesday: '07:00 - 21:00',
      thursday: '07:00 - 21:00',
      friday: '07:00 - 21:00',
      saturday: '07:00 - 21:00',
      sunday: 'Geschlossen'
    }
  },
  {
    id: '22',
    name: 'E center Löffler',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'EDEKA Löffler - Frische und Vielfalt im Herzen von Winterberg.',
    address: 'Neue Mitte 4, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://www.edeka.de/',
    imageFallback: 'EL',
  },
  {
    id: '23',
    name: 'ALDI Nord',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'Hochwertige Produkte zum Original ALDI Preis.',
    address: 'Neue Mitte 3, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://www.aldi-nord.de/',
    imageFallback: 'AN',
  },
  {
    id: '24',
    name: 'Dorfladen Wilmes',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'Lebensmittel und Artikel für den täglichen Bedarf.',
    address: 'Wiesenstr. 12, 59955 Winterberg',
    district: 'Silbach',
    phone: '02983 1774',
    imageFallback: 'DW',
  },
  {
    id: '25',
    name: 'EDEKA Lingenauber',
    category: 'Einzelhandel',
    subcategory: 'Supermarkt',
    description: 'EDEKA Markt mit vielfältigem Sortiment.',
    address: 'Nuhnetalstraße 46, 59955 Winterberg',
    district: 'Züschen',
    website: 'https://www.edeka.de/',
    imageFallback: 'EL',
  },
  {
    id: '26',
    name: 'Tennisplätze Niedersfeld',
    category: 'Freizeit',
    subcategory: 'Tennisplätze',
    description: 'Tennisverein in Niedersfeld mit 3 Sandplätzen.',
    address: 'An der Hille 6b, 59955 Winterberg',
    district: 'Niedersfeld',
    website: 'http://www.sv-niedersfeld.de',
    imageFallback: 'SVN',
  },
  {
    id: '27',
    name: 'Tennisplätze Züschen',
    category: 'Freizeit',
    subcategory: 'Tennisplätze',
    description: 'Tennisverein in Züschen mit Sandplätzen.',
    address: 'Schützenstraße 5, 59955 Winterberg',
    district: 'Züschen',
    phone: '02981 2541',
    imageFallback: 'TUS',
  },
  {
    id: '28',
    name: 'Tennisplätze Winterberg',
    category: 'Freizeit',
    subcategory: 'Tennisplätze',
    description: 'Tennisverein in Winterberg Winterberg mit Sandplätzen.',
    address: 'Fichtenweg 14, 59955 Winterberg',
    district: 'Winterberg',
    website: 'http://www.tc-winterberg.de',
    imageFallback: 'TC',
  },
  {
    id: '29',
    name: 'Tennisplätze Siedlinghausen',
    category: 'Freizeit',
    subcategory: 'Tennisplätze',
    description: 'Tennisverein in Siedlinghausen (keine Sandplätze).',
    address: 'Grimmeweg 9, 59955 Winterberg',
    district: 'Siedlinghausen',
    website: 'mailto:bm.hoemberg@gmail.com',
    imageFallback: 'TC',
  },
  {
    id: '30',
    name: 'VfR Winterberg 1921 e.V.',
    category: 'Freizeit',
    subcategory: 'Fußballvereine',
    description: 'Fußballverein in Winterberg Winterberg.',
    address: 'Oberhofer Weg 9, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02985 979916',
    email: 'info@vfr-winterberg.de',
    website: 'http://vfr-winterberg.de/',
    imageFallback: 'VfR',
  },
  {
    id: '31',
    name: 'TuS Züschen e.V.',
    category: 'Freizeit',
    subcategory: 'Fußballvereine',
    description: 'Fußball- und Sportverein in Züschen.',
    address: 'Junkerstraße 38, 59955 Winterberg',
    district: 'Züschen',
    email: 'vorstand@tus-zueschen.de',
    website: 'http://www.tus-zueschen.de/',
    imageFallback: 'TuS',
  },
  {
    id: '32',
    name: 'Spiel- und Sportverein Silbach 1923 e.V.',
    category: 'Freizeit',
    subcategory: 'Fußballvereine',
    description: 'Sportverein in Silbach.',
    address: 'Am Schieferberg 2, 59955 Winterberg',
    district: 'Silbach',
    imageFallback: 'SSV',
  },
  {
    id: '33',
    name: 'FC Siedlinghausen 1920 e.V',
    category: 'Freizeit',
    subcategory: 'Fußballvereine',
    description: 'Fußballabteilung (2 Seniorenmannschaften und mehrere Jugendmannschaften), Breitensport (Gymnastik und Faszientraining), Wirbelsäulengymnastik, Qi Gong, Meditation.',
    address: 'Sorpestraße 41, 59955 Winterberg',
    district: 'Siedlinghausen',
    email: 'trippemichael17@gmail.com',
    imageFallback: 'FCS',
  },
  {
    id: '34',
    name: 'FC Hilletal 2003',
    category: 'Freizeit',
    subcategory: 'Fußballvereine',
    description: 'Fußballverein in Niedersfeld.',
    address: 'An der Hille 6 a, 59955 Winterberg',
    district: 'Niedersfeld',
    phone: '02985 979916',
    email: 'info@fc-hilletal.de',
    website: 'http://www.fc-hilletal.de/',
    imageFallback: 'FCH',
  },
  {
    id: '35',
    name: 'CEB-Steuerberater',
    category: 'Dienstleistungen',
    subcategory: 'Steuerberater',
    description: 'Ihre Steuerberatung in Winterberg.',
    address: 'Hauptstraße 26, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92560',
    imageFallback: 'CEB',
  },
  {
    id: '36',
    name: 'Kruse Brickenstein & Partner',
    category: 'Dienstleistungen',
    subcategory: 'Steuerberater',
    description: 'Wirtschaftsprüfer und Steuerberater.',
    address: 'Franziskusstraße 9, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92060',
    imageFallback: 'KBP',
  },
  {
    id: '37',
    name: 'Wingenbach & Partner mbB',
    category: 'Dienstleistungen',
    subcategory: 'Steuerberater',
    description: 'Steuerberater in Silbach.',
    address: 'Wiesenstraße 35, 59955 Winterberg',
    district: 'Silbach',
    phone: '02983 969260',
    imageFallback: 'WP',
  },
  {
    id: '38',
    name: 'BSK Steuerberatung GmbH',
    category: 'Dienstleistungen',
    subcategory: 'Steuerberater',
    description: 'Steuerberatungsgesellschaft in Züschen.',
    address: 'An d. Ebenau 4, 59955 Winterberg',
    district: 'Züschen',
    phone: '02981 92530',
    imageFallback: 'BSK',
  },
  {
    id: '39',
    name: 'Lückel & Partner',
    category: 'Dienstleistungen',
    subcategory: 'Steuerberater',
    description: 'Unternehmens- und Steuerberatung in Siedlinghausen.',
    address: 'Hochsauerlandstraße 78b, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02751 93636',
    imageFallback: 'LP',
  },
  {
    id: '40',
    name: 'Werbeagentur netzpepper',
    category: 'Dienstleistungen',
    subcategory: 'Marketingdienstleistungen',
    description: 'Werbeagentur und Webdesign in Winterberg.',
    address: 'Wernsdorfer Str. 1, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9287580',
    imageFallback: 'WN',
  },
  {
    id: '41',
    name: 'DIVE INN GmbH',
    category: 'Dienstleistungen',
    subcategory: 'Marketingdienstleistungen',
    description: 'Werbeagentur für ganzheitliche Kommunikation.',
    address: 'Remmeswiese 30, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9879997',
    imageFallback: 'DI',
  },
  {
    id: '42',
    name: 'Werbeagentur WERBSTATT',
    category: 'Dienstleistungen',
    subcategory: 'Marketingdienstleistungen',
    description: 'Ihre Werbeagentur in Siedlinghausen.',
    address: 'Senge-Platten-Straße 2, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02983 1632',
    imageFallback: 'WW',
  },
  {
    id: '43',
    name: 'Jeffry Chust Design und Advertising e.K.',
    category: 'Dienstleistungen',
    subcategory: 'Marketingdienstleistungen',
    description: 'Design und Advertising in Winterberg.',
    address: 'Oberhofer Weg 8, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'JC',
  },
  {
    id: '44',
    name: 'SICHTBAR SEO - Simon Kräling',
    category: 'Dienstleistungen',
    subcategory: 'Marketingdienstleistungen',
    description: 'Simon Kräling ist Berater für digitale Sichtbarkeit aus Winterberg im Sauerland. Er unterstützt Unternehmen branchenübergreifend dabei, ihre Zielgruppen genau dort zu erreichen, wo sie suchen: in klassischen Suchmaschinen sowie in modernen KI-Suchsystemen (Generative Engine Optimization - GEO). Durch diese Kombination verbindet er technisches Know-how mit praxisnahen Strategien. So schafft er für seine Kunden mehr digitale Unabhängigkeit und messbaren Erfolg.',
    isPremium: true,
    address: 'Schanzenstraße 28, 59955 Winterberg',
    district: 'Winterberg',
    phone: '01520 6542996',
    imageFallback: 'SS',
  },
  {
    id: '45',
    name: 'Matthias Rappel Rechtsanwalt und Notar',
    category: 'Dienstleistungen',
    subcategory: 'Rechtsanwälte',
    description: 'Rechtsanwalt und Notar in Winterberg.',
    address: '59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92090',
    imageFallback: 'MR',
  },
  {
    id: '46',
    name: 'Rechtsanwalt Ralph Schmitz-Engemann',
    category: 'Dienstleistungen',
    subcategory: 'Rechtsanwälte',
    description: 'Rechtsanwalt in Winterberg.',
    address: '59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 6751',
    imageFallback: 'RS',
  },
  {
    id: '47',
    name: 'Volker Wulf Rechtsanwalt',
    category: 'Dienstleistungen',
    subcategory: 'Rechtsanwälte',
    description: 'Rechtsanwalt in Winterberg.',
    address: '59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92210',
    imageFallback: 'VW',
  },
  {
    id: '48',
    name: 'Marion Stockhausen Rechtsanwältin',
    category: 'Dienstleistungen',
    subcategory: 'Rechtsanwälte',
    description: 'Rechtsanwältin in Winterberg.',
    address: '59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 7001',
    imageFallback: 'MS',
  },
  {
    id: '49',
    name: 'Schliwa Peter Rechtsanwalt',
    category: 'Dienstleistungen',
    subcategory: 'Rechtsanwälte',
    description: 'Rechtsanwalt in Winterberg.',
    address: '59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 3883',
    imageFallback: 'SP',
  },
  {
    id: '100',
    name: 'Insider Fashion Store Winterberg',
    category: 'Einzelhandel',
    subcategory: 'Bekleidung',
    description: 'Bekleidungsgeschäft',
    address: 'Am Waltenberg 21, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9277788',
    imageFallback: 'IF',
  },
  {
    id: '101',
    name: 'Street Point Winterberg',
    category: 'Einzelhandel',
    subcategory: 'Bekleidung',
    description: 'Bekleidungsgeschäft',
    address: 'Hauptstraße 4, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 899500',
    imageFallback: 'SP',
  },
  {
    id: '102',
    name: 'MODEORTH Winterberg GmbH',
    category: 'Einzelhandel',
    subcategory: 'Bekleidung',
    description: 'Herrenmodengeschäft',
    address: 'Hauptstraße 11, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 1775',
    imageFallback: 'MW',
  },
  {
    id: '103',
    name: 'Lütkemeier Modehaus',
    category: 'Einzelhandel',
    subcategory: 'Bekleidung',
    description: 'Bekleidungsgeschäft',
    address: 'Am Waltenberg 30, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 6013',
    imageFallback: 'LM',
  },
  {
    id: '104',
    name: 'Bessmann Mode & Sport (Outlet)',
    category: 'Einzelhandel',
    subcategory: 'Bekleidung',
    description: 'Bekleidungsgeschäft (Outlet)',
    address: 'Neue Mitte 3, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 8994180',
    imageFallback: 'BM',
  },
  {
    id: '105',
    name: 'Zeitlos',
    category: 'Einzelhandel',
    subcategory: 'Bekleidung',
    description: 'Bekleidungsgeschäft',
    address: 'Am Waltenberg 19, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 7937',
    imageFallback: 'ZL',
  },
  {
    id: '106',
    name: 'K-OFFICE BÜRODESIGN',
    category: 'Einzelhandel',
    subcategory: 'Bürobedarf',
    description: 'Bürodesign und individuelle Beratung. Vertrieb von Büroeinrichtungen. Inhaber: Burkhard Kräling.',
    address: 'Buchenweg 17, 59955 Winterberg',
    district: 'Winterberg',
    phone: '0170 220 1240',
    email: 'info@k-office.eu',
    imageFallback: 'KO',
  },
  {
    id: '107',
    name: 'Dorf Alm Winterberg',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Tiroler Küche in traditionellem Ambiente.',
    address: 'Am Waltenberg 35, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'DA',
  },
  {
    id: '108',
    name: 'Restaurant Heimatliebe',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Gemütliches Lokal mit Hausmannskost',
    address: 'Am Waltenberg 2, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'RH',
  },
  {
    id: '109',
    name: 'Restaurant Rot & Kehlchen',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Restaurant',
    address: 'Hellenstraße 2, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'RK',
  },
  {
    id: '110',
    name: 'Restaurant Forsthaus',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Restaurant',
    address: 'Orkestraße 14, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'RF',
  },
  {
    id: '111',
    name: 'Bistorant Uppu',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Einfaches Lokal für Burger und Brunch',
    address: 'Am Waltenberg 19, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'BU',
  },
  {
    id: '112',
    name: 'Restaurant Bödefelder',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Restaurant',
    address: 'Hauptstraße 3, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'RB',
  },
  {
    id: '113',
    name: 'Pasta & Wine Winterberg',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Zwangloses Lokal für italienische Pasta',
    address: 'Am Waltenberg 34, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'PW',
  },
  {
    id: '114',
    name: 'Restaurant - Der Brabander',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Restaurant',
    address: 'Am Waltenberg 63, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'DB',
  },
  {
    id: '115',
    name: 'Die Sperre',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Restaurant',
    address: 'Sorpestraße 80, 59955 Winterberg',
    district: 'Siedlinghausen',
    imageFallback: 'DS',
  },
  {
    id: '116',
    name: 'Panorama Restaurant & Café',
    category: 'Gastronomie',
    subcategory: 'Restaurant',
    description: 'Bergpanorama und internationale Speisen',
    address: 'Kappe 2d, 59955 Winterberg',
    district: 'Winterberg',
    imageFallback: 'PR',
  },
  {
    id: '117',
    name: 'Sparkasse Mitten im Sauerland - BeratungsCenter',
    category: 'Dienstleistungen',
    subcategory: 'Banken',
    description: 'Bank und Serviceleistungen.',
    address: 'Am Waltenberg 23, 59955 Winterberg',
    district: 'Winterberg',
    phone: '0291 2080',
    imageFallback: 'SM',
  },
  {
    id: '118',
    name: 'Volksbank Sauerland eG, Beratungszentrum Winterberg',
    category: 'Dienstleistungen',
    subcategory: 'Banken',
    description: 'Bank und Beratungszentrum.',
    address: 'Poststraße 3, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92900',
    imageFallback: 'VB',
  },
  {
    id: '119',
    name: 'Sparkasse Mitten im Sauerland BeratungsCenter Siedlinghausen',
    category: 'Dienstleistungen',
    subcategory: 'Banken',
    description: 'Bank und Serviceleistungen.',
    address: 'Hochsauerlandstr. 17, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '0291 2080',
    email: 'info@sparkasse-mis.de',
    imageFallback: 'SM',
  },
  {
    id: '120',
    name: 'Sparkasse Mitten im Sauerland - SB Center',
    category: 'Dienstleistungen',
    subcategory: 'Banken',
    description: 'Geldtransferdienst und Bank.',
    address: 'Nuhnetalstraße 54, 59955 Winterberg',
    district: 'Züschen',
    phone: '0291 2080',
    imageFallback: 'SM',
  },
  {
    id: '121',
    name: 'Sparkasse Mitten im Sauerland - BeratungsCenter',
    category: 'Dienstleistungen',
    subcategory: 'Banken',
    description: 'Bank und Serviceleistungen.',
    address: 'Ruhrstraße 34, 59955 Winterberg',
    district: 'Niedersfeld',
    phone: '0291 2080',
    imageFallback: 'SM',
  },
  {
    id: '122',
    name: 'Volksbank Brilon, Filiale Niedersfeld',
    category: 'Dienstleistungen',
    subcategory: 'Banken',
    description: 'Bank und Serviceleistungen.',
    address: 'Ruhrstraße 24-26, 59955 Winterberg',
    district: 'Niedersfeld',
    phone: '02985 425',
    imageFallback: 'VB',
  },
  {
    id: '123',
    name: 'Kletterwald Winterberg - Erlebnisberg Kappe',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Klettern - Erlebnisberg Kappe.',
    address: 'Am Waltenberg 115, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9296433',
    website: 'https://www.erlebnisbergkappe.de/',
    imageFallback: 'KW',
  },
  {
    id: '124',
    name: 'BIKEPARK WINTERBERG',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Bikepark am Berghang mit Sesselliften zu den Bergstrecken im Wald sowie ein Bikeverleih.',
    address: 'Kapperundweg 3, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://www.erlebnisbergkappe.de/',
    imageFallback: 'BW',
  },
  {
    id: '125',
    name: 'Panorama-Erlebnis-Brücke',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Die Panorama-Erlebnis-Brücke in Winterberg mit Aussichtsplattformen.',
    address: 'Kappe 2c, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9296433',
    website: 'https://www.erlebnisbergkappe.de/',
    imageFallback: 'PB',
  },
  {
    id: '126',
    name: 'Abenteuergolf Winterberg - Erlebnisberg Kappe',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Minigolfplatz am Erlebnisberg Kappe.',
    address: 'Kappe, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9296433',
    website: 'https://www.erlebnisbergkappe.de/',
    imageFallback: 'AW',
  },
  {
    id: '127',
    name: 'Sommerrodelbahn Winterberg - Erlebnisberg Kappe',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Das Herzstück am Erlebnisberg Kappe, beliebt bei Groß und Klein.',
    address: 'Kappe 2b, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9296433',
    website: 'https://www.erlebnisbergkappe.de/',
    imageFallback: 'SW',
  },
  {
    id: '128',
    name: 'Adventure Golf Winterberg',
    category: 'Freizeit',
    subcategory: 'Outdoor-Freizeitgebiet',
    description: 'Gespielt wird auf abwechslungsreichen Bahnen mit verschiedenen Hindernissen.',
    address: 'Am Sportpl. 4, 59955 Winterberg',
    district: 'Grönebach',
    phone: '02985 9698636',
    website: 'https://adventuregolf-winterberg.de',
    imageFallback: 'AG',
  },
  {
    id: '129',
    name: 'Holocafé Winterberg - Virtual Reality Gaming',
    category: 'Freizeit',
    subcategory: 'Indoor-Spielplätze',
    description: 'Virtual Reality Gaming (ideal für Familien, JGAs, Events oder als Indoor-Schlechtwetteralternative)',
    address: 'Remmeswiese 3, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9277650',
    website: 'https://holocafe.de',
    imageFallback: 'HC',
  },
  {
    id: '130',
    name: 'Full-One Lasertag Winterberg',
    category: 'Freizeit',
    subcategory: 'Indoor-Spielplätze',
    description: 'Indoor Arena Full-One Lasertag Winterberg Kindergeburtstage JGA & Events Gut und Schlechtwetter Alternative',
    address: 'Remmeswiese 3, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9283918',
    website: 'https://full-one-lasertag-winterberg.de',
    imageFallback: 'FL',
  },
  {
    id: '131',
    name: 'Autohaus Friedrich Hoffmann',
    category: 'Einzelhandel',
    subcategory: 'Autohäuser',
    description: 'Ihr VW, Audi & VW Nutzfahrzeuge Autohaus in Winterberg. Erstklassiger Service rund um Ihr Auto.',
    address: 'Remmeswiese 24, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92070',
    website: 'https://www.friedrich-hoffmann.de',
    imageFallback: 'AH',
  },
  {
    id: '132',
    name: 'Autohaus Pöllmann',
    category: 'Einzelhandel',
    subcategory: 'Autohäuser',
    description: 'Ihr Toyota Servicepartner sowie Neuwagen, Gebrauchtwagen, Werkstatt weiterer Marken.',
    address: 'Remmeswiese 22, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 92940',
    website: 'https://www.autohaus-poellmann.de',
    imageFallback: 'AP',
  },
  {
    id: '133',
    name: 'Schütte-Automobile',
    category: 'Einzelhandel',
    subcategory: 'Autohäuser',
    description: 'Autohändler in Winterberg. Verkauf von Neu- und Gebrauchtwagen.',
    address: 'Remmeswiese 2a, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 928190',
    website: 'https://www.schuette-automobile.de',
    imageFallback: 'AS',
  },
  {
    id: '134',
    name: 'UplandParcs Sauerland',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Ferienparks',
    description: 'Erleben Sie einen traumhaften Urlaub im UplandParcs Sauerland! Luxuriöse Unterkünfte inmitten der Natur.',
    address: 'Winterberg',
    district: 'Winterberg',
    website: 'https://www.uplandparcs.de',
    imageFallback: 'UPS',
  },
  {
    id: '135',
    name: 'UplandParcs Winterberg',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Ferienparks',
    description: 'Entdecken Sie UplandParcs Winterberg - luxuriöse Ferienhäuser in toller Lage. Ideal für Familien und Aktivurlauber.',
    address: 'Winterberg',
    district: 'Winterberg',
    website: 'https://www.uplandparcs.de',
    imageFallback: 'UPW',
  },
  {
    id: '136',
    name: 'UplandParcs Bergblick',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Ferienwohnungen',
    description: 'Ferienwohnung mit fantastischem Bergblick.',
    address: 'Winterberg',
    district: 'Winterberg',
    website: 'https://www.uplandparcs.de',
    imageFallback: 'UPB',
  },
  {
    id: '137',
    name: 'UplandParcs Bergresidence',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Ferienwohnungen',
    description: 'Luxuriöse Ferienwohnung Bergresidence.',
    address: 'Holtener Weg, 59955 Winterberg',
    district: 'Winterberg',
    website: 'https://www.uplandparcs.de',
    imageFallback: 'UPR',
  },
  {
    id: '138',
    name: 'UplandParcs Dumel',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Ferienhäuser',
    description: 'Komfortables Ferienhaus Dumel für einen entspannten Aufenthalt.',
    address: 'Winterberg',
    district: 'Winterberg',
    website: 'https://www.uplandparcs.de',
    imageFallback: 'UPD',
  },
  {
    id: '139',
    name: 'Hapimag Resort Winterberg',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Ferienparks',
    description: 'Hapimag Resort in Winterberg. Urlaub für die ganze Familie mit Wellness und tollen Aktivitäten.',
    address: 'Holzruhrstraße 1, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 8080',
    website: 'https://www.hapimag.com',
    imageFallback: 'HM',
  },
  {
    id: '140',
    name: 'Der Brabander',
    category: 'Hotels und Unterkünfte',
    subcategory: 'Hotels',
    description: 'Das bekannte und beliebte Hotel in Winterberg. Wellness, Gastronomie und direkte Nähe zum Skilift.',
    address: 'Am Waltenberg 65, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9320',
    website: 'https://www.brabander.nl',
    imageFallback: 'DB',
  },
  {
    id: 'daswerk-friseure',
    name: 'DasWERK - Die Friseure',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon in Winterberg.',
    address: 'Hochsauerlandstraße 78b, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02983 9799788',
    isPremium: false,
    imageFallback: 'DW'
  },
  {
    id: 'hair-anselm-winkler',
    name: 'Hair by Anselm Winkler',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon mit Dienstleistungen wie Haarefärben, Haarstyling, Balayage, Blow-out und Dauerwellen.',
    address: 'Wernsdorfer Str. 2, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 1399',
    isPremium: false,
    imageFallback: 'HW'
  },
  {
    id: 'winterberger-barber-simply-hair',
    name: 'Winterberger Barber: Simply Hair',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Herrenfriseur in Winterberg.',
    address: 'Am Waltenberg 50, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9255808',
    website: 'https://winterbergerbarber.de',
    isPremium: false,
    imageFallback: 'SH'
  },
  {
    id: 'brieden-friseur',
    name: 'Brieden - Ihr Friseur in Winterberg',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Ihr Friseur in Winterberg. Spezialisiert auf Haarefärben und Haarstyling.',
    address: 'Hagenstraße 8, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 413',
    isPremium: false,
    imageFallback: 'BF'
  },
  {
    id: 'amers-style',
    name: "Amer's Style",
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon. Dienstleistungen umfassen Haarstyling, Haarefärben und Augenbrauen zupfen.',
    address: 'Hauptstraße 5, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 9271848',
    isPremium: false,
    imageFallback: 'AS'
  },
  {
    id: 'haarschneiderei',
    name: 'Haarschneiderei',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon in Winterberg mit Fokus auf Haarefärben und Haarstyling.',
    address: 'Marktstraße 24, 59955 Winterberg',
    district: 'Winterberg',
    phone: '02981 899898',
    isPremium: false,
    imageFallback: 'HS'
  },
  {
    id: 'hairfeeling-kai-padberg',
    name: 'Hairfeeling Kai Padberg',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon im Ortsteil Hildfeld.',
    address: 'Hildfelder Str. 37, 59955 Winterberg',
    district: 'Hildfeld',
    phone: '02985 1046',
    isPremium: false,
    imageFallback: 'KP'
  },
  {
    id: 'hairlounge-by-hannah',
    name: 'Hairlounge by Hannah',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon in Züschen.',
    address: 'Mittelstraße 20, 59955 Winterberg',
    district: 'Züschen',
    isPremium: false,
    imageFallback: 'HH'
  },
  {
    id: 'friseursalon-koch',
    name: 'Friseursalon Koch',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon im Ortsteil Züschen.',
    address: 'Mollseifener Str. 2, 59955 Winterberg',
    district: 'Züschen',
    phone: '02981 6899',
    isPremium: false,
    imageFallback: 'FK'
  },
  {
    id: 'cutja',
    name: 'Cutja',
    category: 'Handwerk',
    subcategory: 'Friseur',
    description: 'Friseursalon in Siedlinghausen. Spezialisiert auf Brautfrisuren, Flechtfrisuren und Hochsteckfrisuren.',
    address: 'Negertstraße 1, 59955 Winterberg',
    district: 'Siedlinghausen',
    phone: '02983 1256',
    isPremium: false,
    imageFallback: 'CJ'
  }
];

export const themes: Record<ThemeKey, ThemeConfig> = {
  nature: {
    name: 'Klassisch Natur',
    description: 'Erdige Grüntöne mit modernen orangefarbenen Akzenten.',
    bgPage: 'bg-stone-50',
    textBase: 'text-stone-900',
    textMuted: 'text-stone-500',
    primaryBtn: 'bg-orange-500 hover:bg-orange-600 text-white shadow-lg shadow-orange-500/30 transition-all',
    categoryTagActive: 'bg-gradient-to-r from-orange-400 to-orange-500 text-white shadow-md shadow-orange-500/20',
    categoryTagInactive: 'bg-white/40 text-stone-700 hover:bg-white/70 hover:text-orange-600 backdrop-blur-md border border-white/50 transition-colors',
    cardBg: 'bg-white/60 backdrop-blur-xl',
    cardBorder: 'border-white/60 hover:border-orange-200 transition-colors',
    cardShadow: 'shadow-[0_8px_30px_rgb(0,0,0,0.04)]',
    iconAccent: 'text-orange-500',
    headerBg: 'bg-emerald-900/95 backdrop-blur-md text-stone-50',
    bottomRightImage: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=1600&auto=format&fit=crop',
  },
  winter: {
    name: 'Winterzauber',
    description: 'Kühle, kristalline Blautöne, passend zur Wintersport-Metropole.',
    bgPage: 'bg-slate-50',
    textBase: 'text-slate-900',
    textMuted: 'text-slate-500',
    primaryBtn: 'bg-sky-600 hover:bg-sky-700 text-white',
    categoryTagActive: 'bg-sky-600 text-white',
    categoryTagInactive: 'bg-slate-200 text-slate-700 hover:bg-slate-300',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-100/50',
    cardShadow: 'shadow-md shadow-slate-200/50',
    iconAccent: 'text-sky-500',
    headerBg: 'bg-white text-slate-900 border-b border-slate-200',
  },
  modern: {
    name: 'Modern Business',
    description: 'Klarer Kontrast, schlichtes Design und professioneller Fokus.',
    bgPage: 'bg-neutral-100',
    textBase: 'text-neutral-900',
    textMuted: 'text-neutral-500',
    primaryBtn: 'bg-black hover:bg-neutral-800 text-white rounded-none',
    categoryTagActive: 'bg-black text-white rounded-none',
    categoryTagInactive: 'bg-neutral-200 text-neutral-800 hover:bg-neutral-300 rounded-none',
    cardBg: 'bg-white rounded-none',
    cardBorder: 'border-neutral-300 rounded-none',
    cardShadow: '',
    iconAccent: 'text-neutral-900',
    headerBg: 'bg-black text-white',
  },
  alpine: {
    name: 'Gemütlich Alpin',
    description: 'Warme Farben und sanfte Kontraste für rustikale Gemütlichkeit.',
    bgPage: 'bg-orange-50',
    textBase: 'text-stone-900',
    textMuted: 'text-stone-600',
    primaryBtn: 'bg-orange-700 hover:bg-orange-800 text-white',
    categoryTagActive: 'bg-orange-700 text-white',
    categoryTagInactive: 'bg-orange-200/50 text-orange-900 hover:bg-orange-200',
    cardBg: 'bg-amber-50/50',
    cardBorder: 'border-orange-200/60',
    cardShadow: 'shadow-sm',
    iconAccent: 'text-orange-600',
    headerBg: 'bg-orange-100 text-orange-950 border-b border-orange-200',
  },
  panorama: {
    name: 'Panorama Blur',
    description: 'Vollflächiges Hintergrundbild mit leichtem Blur, für maximale Atmosphäre.',
    bgPage: 'bg-slate-900',
    textBase: 'text-slate-100',
    textMuted: 'text-slate-300',
    primaryBtn: 'bg-emerald-600 hover:bg-emerald-700 text-white',
    categoryTagActive: 'bg-emerald-600 text-white',
    categoryTagInactive: 'bg-slate-800/60 text-slate-200 hover:bg-slate-700/60 backdrop-blur-md',
    cardBg: 'bg-slate-900/60 backdrop-blur-md',
    cardBorder: 'border-slate-700/50',
    cardShadow: 'shadow-xl',
    iconAccent: 'text-emerald-400',
    headerBg: 'bg-slate-900/80 backdrop-blur-lg border-b border-white/10',
    backgroundImage: 'https://images.unsplash.com/photo-1498860714247-49f9dfccafac?q=80&w=2000&auto=format&fit=crop', // Winterberg scenery
    backgroundBlur: 'blur-sm',
    backgroundOpacity: 'opacity-40',
  },
  glass: {
    name: 'Glassmorphism',
    description: 'Helles, durchlässiges Design mit einem dekorativen Natur-Element unten rechts.',
    bgPage: 'bg-emerald-50',
    textBase: 'text-emerald-950',
    textMuted: 'text-emerald-700/80',
    primaryBtn: 'bg-emerald-800 hover:bg-emerald-900 text-white',
    categoryTagActive: 'bg-emerald-800 text-white',
    categoryTagInactive: 'bg-white/40 text-emerald-900 hover:bg-white/60 backdrop-blur-md border border-white/50',
    cardBg: 'bg-white/60 backdrop-blur-xl',
    cardBorder: 'border-white/60',
    cardShadow: 'shadow-[0_8px_30px_rgb(0,0,0,0.04)]',
    iconAccent: 'text-emerald-700',
    headerBg: 'bg-white/40 backdrop-blur-xl border-b border-white/60',
    bottomRightImage: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=1600&auto=format&fit=crop', // Forest scenery
  },
  dark: {
    name: 'Dark Mode',
    description: 'Dunkles Farbschema für das gesamte Verzeichnis.',
    bgPage: 'bg-slate-900',
    textBase: 'text-slate-100',
    textMuted: 'text-slate-400',
    primaryBtn: 'bg-emerald-600 hover:bg-emerald-700 text-white',
    categoryTagActive: 'bg-emerald-600 text-white',
    categoryTagInactive: 'bg-slate-800 text-slate-300 hover:bg-slate-700 border border-slate-700',
    cardBg: 'bg-slate-800/80 backdrop-blur-md',
    cardBorder: 'border-slate-700',
    cardShadow: 'shadow-lg shadow-black/20',
    iconAccent: 'text-emerald-400',
    headerBg: 'bg-slate-950 border-b border-slate-800 text-slate-100',
  }
};

export const categories: CategoryGroup[] = [
  { name: 'Hotels und Unterkünfte', subcategories: ['Ferienparks', 'Ferienhäuser', 'Ferienwohnungen', 'Hotels'] },
  { name: 'Handwerk', subcategories: ['KFZ-Werkstätten', 'Schreinereien', 'Wäschereien', 'Dachdecker', 'Elektriker', 'Friseur', 'Heizungsbauer', 'Bauunternehmen', 'Maler & Lackierer'] },
  { name: 'Einzelhandel', subcategories: ['Supermarkt', 'Bekleidung', 'Bürobedarf', 'Autohäuser'] },
  { name: 'Gastronomie', subcategories: ['Restaurant', 'Kneipen und Bars', 'Eisdielen', 'Pizzerien', 'Imbisse', 'Weinstuben'] },
  { name: 'Dienstleistungen', subcategories: ['Steuerberater', 'Marketingdienstleistungen', 'Finanzberatung', 'Rechtsanwälte', 'Banken', 'Versicherungsagenturen'] },
  { name: 'Freizeit', subcategories: ['Indoor-Spielplätze', 'Tennisplätze', 'Fußballvereine', 'Schwimmbäder', 'Outdoor-Freizeitgebiet'] }
];
